### ISSUE TITLE
use with() and paginate() in the same call

### ISSUE THREAD

**Issue by michael-hopkins** [andersao/l5-repository#10]
I'm trying to do something along these lines

    $this->order->with(['orderedBy', 'payment', 'assignedTo', 'orderStatus', 'lineItems.product', 'lineItems.orderLineItemStatus','domain'])->paginate(25);

Before implementing this package (I forget exactly) the page had <15 queries executed. Now it has over 100. Any idea how I can accomplish this? `$this->order is an OrderRepository that uses this package.

**Comment by andersao** [comment]
@michael-hopkins Fixed ;)

**Comment by michael-hopkins** [comment]
well, wasn't that a stupid simple fix. thanks man!
