### ISSUE TITLE
Fractal presenters: Manually include relationship presenter

### ISSUE THREAD

**Issue by jonagoldman** [andersao/l5-repository#101]
I want to include relationships in my presenter.
I know I can ***automatically*** include default relationships by adding this to my Transformer class:

```php
class BookTransformer extends TransformerAbstract
{
    protected $defaultIncludes = [
        'author'
    ];

    // ...
}
```
Now, I want to choose ***manually*** when to add a relationship.
Reading the Fractal docs I see that I need to add this to my Transformer class

```php

class BookTransformer extends TransformerAbstract
{

    protected $availableIncludes = [
        'author'
    ];

    public function transform(Book $book)
    {
        return [
           //  ...
        ];
    }

    public function includeAuthor(Book $book)
    {
        $author = $book->author;
        return $this->item($author, new AuthorTransformer);
    }
}
```

But now I need a way to tell the presenter to include my relationship ('author' in this case)

How can I do that?

**Comment by jonagoldman** [comment]
My current solution:

***Step 1:*** Create new class that extends ```FractalPresenter``` and override the ```parseIncludes()``` method to allow ```$includes``` parameter:

```php
use Prettus\Repository\Presenter\FractalPresenter;

abstract class FractalRelationshipsPresenter extends FractalPresenter
{

    public function parseIncludes($includes = array())
    {

        $request        = app('Illuminate\Http\Request');
        $paramIncludes  = config('repository.fractal.params.include','include');

        if ( $request->has( $paramIncludes ) ) {
            $includes = array_merge($includes, explode(',', $paramIncludes));
        }

        $this->fractal->parseIncludes($includes);

        return $this;
    }

}
```

***Step 2:*** Create new class that extends ```BaseRepository``` and create ```present()``` method to allow to add relationships to the presenter:

```php
use Prettus\Repository\Eloquent\BaseRepository;

abstract class PresentableRepository extends BaseRepository
{

    public function present($relations)
    {
        $this->presenter->parseIncludes($relations);
        return $this;
    }

}
```

***Step 3:*** Update your Presenters and Repositories to extend the new classes in previous steps:

```php
class MyPresenter extends FractalRelationshipsPresenter
{
   
    public function getTransformer()
    {
        return new MyTransformer();
    }
}
```

```php
class MyRepositoryEloquent extends PresentableRepository implements PropertyRepository
{

    public function model()
    {
        return MyModel::class;
    }

    public function presenter()
    {
        return MyPresenter::class;
    }

}
```

***Usage:*** Call the ```present()``` method to include presenter relationships:

```php
class MyController extends Controller
{

    protected $repository;

    public function __construct(MyRepository $repository){
        $this->repository = $repository;
    }

    public function index()
    {
       
        $collection = $this->repository->present(['myrelationship'])->all();
    }
```

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by pat-och** [comment]
hello Jona,

do you think is possible to implement this in the `with()` repository function instead a `present()`?

@jonagoldman
