### ISSUE TITLE
Searching by multiple search fields

### ISSUE THREAD

**Issue by drmmr763** [andersao/l5-repository#102]
Hi All

First off - Thank you for this package. I struggled for a while implementing what I wanted: Fractal, URL query searches, and some way to use existing models in my L5 app. This puts all those things together in a lovely package.

I'm struggling with one thing, which I think shouldn't be too hard. I simply want to be able to use URL query params to filter my REST api results. My URL should look like this:

```
my-app.local/api/v1/temp?page=2&search=tempType:a;state:FL
```

I have the fields referenced there listed as searchable in the repository:

```
/**
	 * @var array
	 */
	protected $fieldSearchable = [
		'firstName'    => 'like',
		'lastName'     => 'like',
		'address'      => 'like',
		'city'         => 'like',
		'state'        => '=',
		'zip'          => '=',
		'phone'        => '=',
		'email'        => 'like',
		'recruiter'    => '=',
		'tempType'     => '='
	];
```

The first value is actually used properly. If I do:

```
my-app.local/api/v1/temp?page=2&search=tempType:a
```

I'll get the correct results. And If I use the other field, i also get the correct results:
```
my-app.local/api/v1/temp?page=2&search=tempType:a
```

Combining them; the first field is used in the filter but the second is not. 

Testing:
With this URL:
```
my-app.local/api/v1/temp?page=2&search=tempType:a;state:FL
```

I looked into RequestCriteria:
https://github.com/andersao/l5-repository/blob/master/src/Prettus/Repository/Criteria/RequestCriteria.php#L52

I threw a bunch of var-dumps in there:

```
var_dump($searchFields);
var_dump($search);
var_dump($searchData);
```

And it seems to be properly splitting the values out:

`$searchFields:`
```
array (size=2)
  'state' => string 'fl' (length=2)
  'tempType' => string 'a' (length=1)
```

`$fields`
```
array (size=10)
  'firstName' => string 'like' (length=4)
  'lastName' => string 'like' (length=4)
  'address' => string 'like' (length=4)
  'city' => string 'like' (length=4)
  'state' => string '=' (length=1)
  'zip' => string '=' (length=1)
  'phone' => string '=' (length=1)
  'email' => string 'like' (length=4)
  'recruiter' => string '=' (length=1)
  'tempType' => string '=' (length=1)
```

I even checked to make sure it wasn't hitting the null value check:

`$value`
```
string 'fl' (length=2)
string 'a' (length=2)
```

As far as i can tell, I'm doing everything close to correct. But maybe I'm missing something. I'm sure its probably around the where statement that is getting generated or something along those lines. Any ideas on how I can do this would be super helpful. 

Thanks all
Chad

**Comment by drmmr763** [comment]
PS:

Just did some more debugging dumping the query:

```
var_dump($query->toSql());
```
Gives me:
```
string 'select * from `temps` where `state` = ? or `tempType` = ?' (length=57)
```

So clearly this is where the issue is. The question is, how to change that from an "OR" to an "and". 

I think the relevant code is here where there's a check for `modelForceAndWhere`:

https://github.com/andersao/l5-repository/blob/master/src/Prettus/Repository/Criteria/RequestCriteria.php#L51-L53

```
$modelForceAndWhere = false;

$model = $model->where(function ($query) use($fields, $search, $searchData, $isFirstField, $modelForceAndWhere) {
// rest of function
```

as far as I can tell, there's no place for this value to be set or changed. It's set to false and stays false. Again, help i understanding why this is would be awesome.

**Comment by drmmr763** [comment]
Following up:

I didn't see a good way to accomplish what I wanted, and I really wanted to build in some more complex URL query filtering. To do that I created my own custom RequestCriteria. You can see it here:

https://gist.github.com/drmmr763/338c9ab380b533ab2623

The URL parsing functions are borrowed from:
https://github.com/marcelgwerder/laravel-api-handler/blob/master/src/Parser.php#L209

Which lends its self to wonderfully complex queries: 
```
#####Suffixes#####
Suffix        | Operator      | Meaning
------------- | ------------- | -------------
-lk           | LIKE          | Same as the SQL `LIKE` operator
-not-lk       | NOT LIKE      | Same as the SQL `NOT LIKE` operator
-in           | IN            | Same as the SQL `IN` operator
-not-in       | NOT IN        | Same as the SQL `NOT IN` operator
-min          | >=            | Greater than or equal to
-max          | <=            | Smaller than or equal to
-st           | <             | Smaller than
-gt           | >             | Greater than
-not          | !=            | Not equal to
```

If there's interest I'd be happy to generate a pull request with these updates. If not, feel free to borrow the completed class I created. Please keep the attributes to the original parser author as well!

**Comment by jonagoldman** [comment]
Just to let you know, this package seems a little dead. At least I have not seen any issue responses for a few months now.

**Comment by drmmr763** [comment]
Well that's a bummer. There aren't any better alternatives are there?

**Comment by jonagoldman** [comment]
I did not found any alternative, but anyways I am using it in my projects. At the end its just implementing different programming patterns into one repository. You could also dig into the code and see how its built and modify it to fit your needs. I have done it and learned a lot in the process.

**Comment by jonagoldman** [comment]
@drmmr763 I see you are building an API and I think is better for you to use Dingo API (https://github.com/dingo/api) for Laravel.
It handles Response Transformers and Formatters (using Fractal) and also Authentication, API Versioning, Rate Limiting and more.
I was also using the this L5-Repository package but end up switching to Dingo API and only copying the Repository patter from here and doing some modifications.
Good look.

**Comment by andersao** [comment]
Hello guys, the package was not abandoned, just been busy in recent months, so I ended it away from me and not given the necessary support to you, I'm checking each issue and responding.

**Comment by geraldarcega** [comment]
Hi guys! Is there already fix on this issue?

**Comment by netdotter787** [comment]
I found an easy work around.
Just create a new Criteria and use that in the controllers when need and adding a new search parameter in the config/repository.php 

```

'params'    =>   [
            'search'       => 'search',
            'searchFields' => 'searchFields',
            'filter'       => 'filter',
            'orderBy'      => 'orderBy',
            'sortedBy'     => 'sortedBy',
            'with'         => 'with',
            'and'          => 'and'
        ]

```

Then create a new Criteria file, based on the default RequestCriteria.php, with a minor hack
```
if($this->request->get(config('repository.criteria.params.and', false), false) == 'pass')
            {
                $modelForceAndWhere = true;
            } else {
                $modelForceAndWhere = false;
            }
```

so we can use it like 
```
<site_name>/api/v1/albums?search=artist_id:1;name:Ba&searchFields=name:like;artist_id:=&and=pass
```
