### ISSUE TITLE
skipPresenter() does not work when Repository implements CacheableInterface

### ISSUE THREAD

**Issue by digitlimit** [andersao/l5-repository#103]
When Repository implements CacheableInterface skipPresenter() does not work when called.

     <?php namespace App\Repositories;

      use Prettus\Repository\Eloquent\BaseRepository;
      use Prettus\Repository\Criteria\RequestCriteria;
      use Prettus\Repository\Contracts\CacheableInterface;
      use Prettus\Repository\Traits\CacheableRepository;

      use App\Models\Post;
      use App\Presenters\PostPresenter;
 
      class PostRepository extends BaseRepository implements CacheableInterface
      {

           use CacheableRepository;

           protected $fieldSearchable = [
                 'id',
                 'email'
           ];

           public function model()
           {
                 return Post::class;
           }

           public function presenter()
           {
                return PostPresenter::class;
           }

           public function boot(){
                 $this->pushCriteria(app(RequestCriteria::class));
           }
      }

**Comment by andersao** [comment]
Hi @digitlimit 

I will check this

**Comment by ionut-tanasa** [comment]
@digitlimit because it's cached. You have to skip cache too.

`$repository->skipCache()->skipPresenter()->all()`
