### ISSUE TITLE
How can I use Laravel Sluggable with this package?

### ISSUE THREAD

**Issue by devfelipereis** [andersao/l5-repository#105]
Hello!

I'm using this package and it's working fine. I'm new in this pattern so sometimes I don't know how to do some stuff.

I'm using Larevel Sluggable(https://github.com/cviebrock/eloquent-sluggable) and I have a method called: findBySlugOrId
It's called from a trait(SluggableTrait). 

When I try: $this->repository->findBySlugOrId($slug)

I get a error that "findBySlugOrId" doesn't exists. To fix this, in my "EventRepositoryEloquent", i create this method:

public function findBySlugOrId($idOrSlug)
{
     return $this->model->findBySlugOrId($idOrSlug);
}

Then, I call that method using Event object and this works. But, I'm doing this right? 

Or I have a better way to do this? Cause I if I need another method from there, I need to create another method inside "EventRepositoryEloquent" and so son :/

Thank you!

**Comment by andersao** [comment]
Hi @devfelipereis 

Yes, if you need new methods, you can simply add the methods in its interface, if using, and then implement the method in your repository. That way you get better organize your project.

**Comment by devfelipereis** [comment]
Good to know. Thank you so much!
