### ISSUE TITLE
dependency to \League\Fractal\TransformerAbstract

### ISSUE THREAD

**Issue by mhndev** [andersao/l5-repository#106]
I have a PostPresenter class as follow 

    <?php

    namespace App\Presenters;

    use App\Transformers\PostTransformer;
    use Prettus\Repository\Presenter\FractalPresenter;

     /**
     * Class PostPresenter
     *
     * @package namespace App\Presenters;
     */
     class PostPresenter extends FractalPresenter
    {
        /**
         * Transformer
         *
         * @return \League\Fractal\TransformerAbstract
         */
        public function getTransformer()
        {
            return new PostTransformer();
        }
    }

you see that getTransformer method returns an instance of  \League\Fractal\TransformerAbstract
but you have'nt added this package as a dependency in composer.json

**Comment by andersao** [comment]
Hi, @mhndev 

In previous versions the package was recorded in `composer.json`, but not necessarily as you need to use the Presenters, I decided to remove the package from dependencies and put as a suggestion, so if you decide to use the package, just add as a `composer.json` the `"league/fractal":"~0.12.0"`
