### ISSUE TITLE
How to remove the namespace data from the array generated by Presenter?

### ISSUE THREAD

**Issue by BlazeNikhilesh** [andersao/l5-repository#107]
I want to remove the key - data - from the array generated by the Presenter.

How can I do that ?

**Comment by jonagoldman** [comment]
You need to change the serializer. Look here: http://fractal.thephpleague.com/serializers/

**Comment by BlazeNikhilesh** [comment]
How can I do that with this package ?

**Comment by jonagoldman** [comment]
You can set a different serializer in the repository.php config file. Just read the Fractal docs because its not possible to completely remove the 'data' key unless you write your own serializer.

**Comment by pat-och** [comment]
see right answer here #554
