### ISSUE TITLE
Custom validation message not coming

### ISSUE THREAD

**Issue by ajeeshcitrus** [andersao/l5-repository#108]
I am using repository pattern using [L5-repository validation][1]. This is my 

controller
----------

    <?php
    
    namespace App\Api\V1\Controllers;
    
    use Request;
    use Dingo;
    use App\Http\Controllers\Controller;
    use App\Repositories\UserRepository;
    use App\Api\V1\Transformers\BankAccountTransformer;
    use Prettus\Validator\Exceptions\ValidatorException;
    use \Prettus\Validator\Contracts\ValidatorInterface;
    use App\Api\V1\Validations\BankAccountValidator;
    
       public function store()
        {
            $request = Request::all();
            try {
                    //Validate request body
                    $this->validator->with(  $request )->passesOrFail(ValidatorInterface::RULE_CREATE);
                    
            }  catch (ValidatorException $e) {
                    throw new Dingo\Api\Exception\StoreResourceFailedException('Unable to add bank account', $e->getMessageBag()); 
      //  Wiki of the project says to use getMessage(), but it throws error

            }
        }

  [1]: https://github.com/andersao/l5-repository#validators

Validation class
----------------

    <?php
    
        namespace App\Api\V1\Validations;
        
        use \Prettus\Validator\Contracts\ValidatorInterface;
        use \Prettus\Validator\LaravelValidator;
        
        class BankAccountValidator extends LaravelValidator {
            
            protected $rules = [
                ValidatorInterface::RULE_CREATE => [
                'bank_name' => 'required'
                ],
                ValidatorInterface::RULE_UPDATE => [
                ]
            ];
            
            protected $messages = [
                'bank_name.required' => 'My custom error'
            ];
           
        }

But I am getting this error  when I use **$e->getMessage()** .

      "message": "Call to a member function isEmpty() on string"

If I am using **$e->getMessageBag()**  I am getting proper error response. But my custom messages are not displayed. A generic message is displayed.

    "errors": {
        "bank_name": [
          "The bank name field is required."
        ]
      }
It actually should have been

    "errors": {
        "bank_name": [
          "My customer error"
        ]
      }

  

dd($e)

    ValidatorException {#505
      #messageBag: MessageBag {#507
        #messages: array:1 [
          "bank_name" => array:1 [
            0 => "The bank name field is required."
          ]
        ]
        #format: ":message"
      }
      #message: ""
      #code: 0
      #file: "/home/vagrant/dev-develop/vendor/prettus/laravel-validation/src/Prettus/Validator/AbstractValidator.php"
      #line: 109
      -trace: array:58 [
        0 => array:3 [
          "call" => "Prettus\Validator\AbstractValidator->passesOrFail()"
          "file" => "/home/vagrant/dev-develop/app/Api/V1/Controllers/BankAccountController.php:61"
          "args" => array:1 [
            0 => "create"
          ]
        ]

**Comment by andersao** [comment]
Hi @ajeeshcitrus 

I will check this. I suggest that you open a ticket on another package also
https://github.com/andersao/laravel-validator/issues

**Comment by dj1020** [comment]
I've already installed `"prettus/laravel-validation": "dev-master"`, but the issue still not solved. I think it 's because I didn't regenerate my entity. I found there may be a typo in the catch part from generator:
```
catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessage()  // HERE is THE PROBLEM
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
```

`'message' => $e->getMessage()` should be `'message' => $e->getMessageBag()`, 
I changed it and it works fine.
