### ISSUE TITLE
Saving Relationship

### ISSUE THREAD

**Issue by jartaud** [andersao/l5-repository#11]
Hello, how should i manage to do something like this:
```php
$category->find(1)->categoryLocalization()
                             ->save(new CategoryLocalization( [
                                             'name' => 'My Category in english',
                                             'lang'=>'en'
] ));
```

**Comment by andersao** [comment]
@jartaud This way does not work?

```php
$category = $this->repository->find(1);
$category->categoryLocalization()
		 ->save(new CategoryLocalization( [
			'name' => 'My Category in english',
			'lang'=>'en'
		]));
```

**Comment by jartaud** [comment]
@andersao Yep! actually I'm doing it this way, but for some reasons I feel bad for using the CategoryLocalization model in the Category repo.

Saddly the following is violating the integrity constraint:

```php
protected function saveCatLoc($catLoc, $category)
    { 
    	foreach ($catLoc['cat_name'] as $key => $value) {

    		$catLocRepository = $this->app->make('NAMESPACE\Repositories\CategoryLocRepository');

    		$catLocRepository->create(['name'=>$value, 'lang'=>$key, 'category_id'=>$category->id]);
	    }
    }
```

**Comment by andersao** [comment]
@jartaud I will work to try to implement something better, I am currently out of time :( But soon will implement something

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by ionut-tanasa** [comment]
```php
$data = [ 'name' => 'My Category in english',  'lang'=>'en' ]

$localization = $this->categoryLocalizaionRepository->skipPresenter(true)->create($data);

$category = $this->categoryRepository->skipPresenter(true)->find(1)->categoryLocalization()->create($localization);
```

This way should work.

**Comment by wdog** [comment]
In my case I have a foreign key and when I use

```php
$localization = $this->categoryLocalizaionRepository->skipPresenter(true)->create($data);
```

I obtain a `Integrity constraint violation`
