### ISSUE TITLE
Not Found Exceptions

### ISSUE THREAD

**Issue by mrbarde** [andersao/l5-repository#122]
So in my controller I wanted to find a user and i did the following
`$user = $this->model->find($id);`
But unfortunate for me I get the following error
*NotFoundHttpException in Handler.php line 102:*
*No query results for model [<Vendor>\<Package>\Models\User].*
But i would like to receive the empty result and then return mine since i'm building an API.
How to I get past the exception?

**Comment by mrbarde** [comment]
So i dicidde to try `$user = $this->model->findWhere(["id" => $id]); and it worked perfectly, for what i wanted.

**Comment by nosun** [comment]
哈哈

**Comment by wangyuanhui** [comment]
you should use try catch.
`try {
$user = $this->model->find($id);
} catch (\Exception $e) {
 ///
}`

**Comment by seegithub** [comment]
i think throwing exception is not a good thing in this context, why? because this is not a type of program error, but rather information that the data does not exist in the database, that's just my opinion
