### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by jake142** [andersao/l5-repository#123]
I use cache on my repositories in my Lumen project. I have setup the cache to use database as driver (cache table). In order for the cache to work l5-repository requires me to have a folder storage/framework/cache (the files are cached both as files and in the DB table). Is it possible to configure l5-repository only to cache in the database and not as file?

**Comment by thiagof** [comment]
Yes sure. You need to configure Laravel Cache `driver` option.
Checkout https://laravel.com/docs/5.1/cache

**Comment by jake142** [comment]
I have done this and the data is cached in the DB (CACHE_DRIVER=database). The problem is that it also cached in the filesystem.
