### ISSUE TITLE
Paginate and findWhere

### ISSUE THREAD

**Issue by quinhone** [andersao/l5-repository#129]
Hello, because I can not use paginate with findWhere?

$this->content->findWhere(['category_id' => '4'])->paginate();

error
Call to undefined method Illuminate\Database\Eloquent\Collection::paginate()

**Comment by elliottmb** [comment]
@quinhone findWhere() returns a Collection generally, which is shown by the error you're receiving. 

If you're wanting to use the paginate() method on the repository, you will need to either use scopeQuery() or a Criteria. Alternatively you could construct a paginator from the collection result of a findWhere().

**Comment by pjmartorell** [comment]
@elliottmb In my opinion, using scopes is a bit hacky, even more when actually the repository pattern tries to decouple from the ORM.

**Comment by Mashpy** [comment]
2 days ago I had solved this problem [this](http://www.mashpy.me/2016/05/add-pagination-with-findwhere.html) way. Hope this article will solve your problem.

**Comment by rushairer** [comment]
When I use scopeQuery() or a Criteria,But the cache key are the same...

**Comment by jacobcyl** [comment]
@Mashpy I don't think your way is the best, maybe use pushCriteria is more elegant.

**Comment by Mashpy** [comment]
@jacobcyl  Can you give me any demo code that I can get the perfect way.
