### ISSUE TITLE
Easiest way to implement the whole thing?

### ISSUE THREAD

**Issue by michael-hopkins** [andersao/l5-repository#13]
I'm currently working on a fairly large project that I would like to put this as an underlying library. I have approximately 26 models. In theory, I don't see anything wrong with getting every model extracted to the repository and able to do validation. Granted, I probably don't need to add validation for `States`/`Countries` as I dont see any new ones being created in the near future. However, I'm not sure this is a small or simple task no matter what way you look at it. Thoughts as to the best way to go about doing that? 

edit: even just a way to combine the repository and validation into a common file would (in theory) reduce the work by 50%.

**Comment by andersao** [comment]
You suggested that validation is within the repository in this way?

```php
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use Prettus\Validator\Contracts\ValidatorInterface;

class PostRepository extends BaseRepository {

    /**
     * Specify Validator class name
     *
     * @return mixed
     */
     protected $rules = [
        ValidatorInterface::RULE_CREATE => [
            'title' => 'required',
            'text'  => 'min:3',
            'author'=> 'required'
        ],
        ValidatorInterface::RULE_UPDATE => [
            'title' => 'required'
        ]
   ];

    /**
     * Specify Model class name
     *
     * @return mixed
     */
    function model(){
       return "App\\Post";
    }

}
```

**Comment by michael-hopkins** [comment]
Something like that yeah. I recognize (and agree with to be honest) the separation of the two and having Validation on its own. For this particular project (and deadline), and to push the least amount of large changes on the team combining them would be ideal I think.

In doing what you've outlined above (and [here](https://github.com/andersao/l5-repository#defining-rules-in-the-repository) which I am hoping wasn't there 24 hours ago) does anything need to be added to the controller or are things business as usual?

**Comment by andersao** [comment]
I implemented the validation own repository based on their need , added more flexibility. All right, you do not need anything else, just add validation rules and ready . If the validation fails will be released an exception from mistakes. I hope they can help you .
