### ISSUE TITLE
chain methods repository

### ISSUE THREAD

**Issue by mandado** [andersao/l5-repository#130]
I tried chain two methods `advertisementsByUserLogged` and `sortByAToZ`
and show error below:

Error:

```
Call to undefined method Illuminate\Database\Query\Builder::sortByAToZ()
```

Code:

```
$this->advertisementRepository->with(['subcategory.category'])->advertisementsByUserLogged()->sortByAToZ()->paginate(10)
```

How can solve this ??

**Comment by pjmartorell** [comment]
There is a related issue that may help you #129 
It's a pity that only some methods can be chained and on top of that, there's no clear documentation about it.

**Comment by nabeeljavaid-vteams** [comment]
Hi,
I checked this package and like overall concept but there are few problem first important issue is that
"Chaining method functionality is not working"

Code:
$this->respository->findWhereIn('id', [1,2,3,4,5])->orderBy('created_at', 'desc')->paginate($limit=5);
