### ISSUE TITLE
Any Reason not Implement `popCriteria()`?

### ISSUE THREAD

**Issue by Abdillah** [andersao/l5-repository#136]
Great library! Thanks.
Well, just out of curiosity : why `BaseRepository` don't have `popCriteria` method?

In my current project, quite a lot I need to reuse my repository in state just before a criteria is pushed.
Well, I resolve this by cloning the repository as well as the property `$criteria`. And recently, I plan to inherit `BaseRepository` class.

With `getCriteria()` not much of a help, because I would not retrieve the result immediately.

**Comment by k1ng440** [comment]
+1
