### ISSUE TITLE
What would the "repository" variant of this line be?

### ISSUE THREAD

**Issue by michael-hopkins** [andersao/l5-repository#14]
I currently have the line of code `Role::whereName('Customer')->first()->users()->paginate(20);` Users and Roles are a many to many relationship. If both of these entities have the repositories created as per this package, how would I go about executing this query? I managed to get it to work with this `$this->role->with(['users'])->findByField('name','Customer')->first()->users()->paginate(20);`, however I'm not posiive this is the most effiecient (db call) way to write it

**Comment by jartaud** [comment]
I think this is the way to go. The only difference here is that you're not referencing directly the Role model.

**Comment by michael-hopkins** [comment]
ah yeah. good call
