### ISSUE TITLE
A question about getSearchableFields method

### ISSUE THREAD

**Issue by tianyong90** [andersao/l5-repository#142]
It seems that the getSearchableFields method is no use, because it always return the $searchableFields field which is an empty array.

**Comment by ionut-tanasa** [comment]
Actually it's used because we use it in RequestCriteria. 
Also you can set which fields are searchable per repository overriding `fieldSearchable` property.

**Comment by tianyong90** [comment]
@ionut-tanasa Got it. Thanks!!
