### ISSUE TITLE
Using with jenssegers/mongodb

### ISSUE THREAD

**Issue by rntorm** [andersao/l5-repository#143]
This repository should work with jenssegers/mongodb also if I'll fork it and replace the Eloquent model with the `use Jenssegers\Mongodb\Model as Eloquent;`? Or are there any other known incompabilities?

**Comment by giolvani** [comment]
I am using this package also, but I cannot create or update. Find registers works fine!

**Comment by rntorm** [comment]
Replace the line I pointed to above and you should be able to also create and update @giolvani. Create atleast works, haven't tested the update yet

**Comment by giolvani** [comment]
Well, it works fine to me now!

In my case, I was forgetting the $fillable fields.
