### ISSUE TITLE
Transformer does not return Collection

### ISSUE THREAD

**Issue by crnkovic** [andersao/l5-repository#147]
Hi!

I'm not sure if this was meant to be, but the transformer and presenter return array. I have to use

@foreach ($posts as $post)
$post[0]['field']
@endforeach

Which is bugging me a lot. Why can't I use standard syntax ($post->field)?

My presenter and transformer look like the ones from the readme.

**Comment by ionut-tanasa** [comment]
Skip the presenter. 


```$this->repository->skipPresenter()->all()```

**Comment by crnkovic** [comment]
That way I have no presenters. I want to have presenters, but I want it to be in the form of Laravel Collection object, not as an array.

**Comment by mrgrain** [comment]
Returning an array is a core functionality of Fractal, which is the default presenter of this package. You will have to implement your own Presenter to achieve this functionality. However, depending on what you try to achieve there might be easier ways to do this (e.g. `collect($posts)->each(function($post) {
    return (object) $post);
});`
