### ISSUE TITLE
Question: findWhere with relation columns

### ISSUE THREAD

**Issue by arthurvasconcelos** [andersao/l5-repository#157]
I've been trying to build a query where I can filter the main result for a table field relationship, I tried using criteria but it still fails.

How could I listen to a query like this:

```sql
SELECT * FROM products p
INNER JOIN product_summary ps ON ps.product_id = p.id 
INNER JOIN summaries s ON s.id = ps.summary_id 
WHERE s.is_category = true 
GROUP BY p.id;
```

I tried setting the column directly in findWhere:

```php
$products = $this->productRepository->with(['summaries'])->findWhere(['is_category' => true]);
```

I tried with criteria:

```php
public function apply($model, RepositoryInterface $repository)
{
    $model = $model->with(['summaries' => function($query) {
        $query->where('is_category', true);
    }]);

    return $model;
}
```

```php
$this->productRepository->pushCriteria(new IsCategoryCriteria());
$products = $this->productRepository->all();
```

But still I keep getting all products. Where am I going wrong?
Many thanks for your help

**Comment by vladiamandii** [comment]
@arthurvasconcelos try this:

    public function apply($model, RepositoryInterface $repository)
    {
        $model = $model->with(['summaries' => function($q){
            $q->where('is_category', true);
        }])->whereHas('summaries', function($query) {
            $query->where('is_category', true);
        });

        return $model;
    }
