### ISSUE TITLE
Relationship with conditions

### ISSUE THREAD

**Issue by devthiagolino** [andersao/l5-repository#158]
how do I use a query that has to have a relationship many to many and have a condition in pivot table or in some of the related tables?

`$this->repository->with(['client', function($query){
      return $query->where(); // ???
    }])->paginate();`

**Comment by vladiamandii** [comment]
@devthiagolino have you tried this? 

    $this->repository->with(['client' => function($query){ $query->where(); }])->paginate();

It should work.

**Comment by jesusvpct** [comment]
Can be a way to do this on the repository? I mean, a function on the repository that returns the results of the condition?
