### ISSUE TITLE
representer issue

### ISSUE THREAD

**Issue by amin101** [andersao/l5-repository#159]
I'm wondering how may i use representer to do jobs like converting output date to my desired one  using something like `$post->presenter()->created_at`?

**Comment by mrgrain** [comment]
You don't. The basic idea of a Presenter is, that you don't touch the data after it got presented. Except to "format" the presented data into the representation of your choice **on a very abstract level**.

For example JSON can be formatted with a single command: `json_encode($presented_data)`. 
For XML it takes a bit more, but it would still work for any kind of data.
```
$xml = new SimpleXMLElement('<root/>');
array_walk_recursive($presented_data, array ($xml, 'addChild'));
```

**Comment by amin101** [comment]
Thanks @mrgrain .how may i benefit of the presenter which is bounded with this package? 
would you please provide me a proper link to learn more about that?

**Comment by mrgrain** [comment]
The default presenter uses [Fractal](http://fractal.thephpleague.com/)

Reading your question again, I might have misinterpreted your request. (Nevertheless, by statement is still correct.) Depending on what exactly you want to do, I would be happy to help you finding a solution.

Do you want to _transform_ a posts `created_at` date into a certain format for output?

**Comment by ionut-tanasa** [comment]
I'd like to decouple fractal in some way.
And use, dunno, another presenter package? 

What do you guys think would be the better way to achieve it?

**Comment by mrgrain** [comment]
Hmm, not sure. It's already pretty decoupled thanks to the `PresenterInterface`. Anyone can simply implement their own presenter.

If you plan to add an other presenter as additional choice: Go ahead!

If you want to remove the `FractalPresenter` implementation from the package: This would be a great loss, since Fractal is IMO the de-facto standard for presenters/transformers/whatever-you-call-them.

**Comment by ionut-tanasa** [comment]
Definetly not removing Fractal :)

Just adding a new one to make it easier and avoid cases like this one.

**Comment by mrgrain** [comment]
Cool :)

I am still not really sure about the use case, but I guess the obvious choice would be a view presenter which will pass the model/collection on to a Blade template and return a ViewResponse.
