### ISSUE TITLE
Find by multiple fields?

### ISSUE THREAD

**Issue by michael-hopkins** [andersao/l5-repository#16]
Either I don't see the method, or the type hinting for the return is incorrect, how would one do the equivalent of `whereX(1)->where('y','>',150)` or something similar?

**Comment by andersao** [comment]
This is not implemented , and today I even had this need. I will implement now .

**Comment by michael-hopkins** [comment]
oh neat. cool thanks!

**Comment by andersao** [comment]
@michael-hopkins Released version 2.0.4 and added the method `findWhere( array $where , $columns = array('*'))` . This helps you?

You can use like this

```php
$this->repository->findWhere(['name'=>'Lorem','age'=>18]);
```

**Comment by michael-hopkins** [comment]
looks awesome. thanks man!

**Comment by michael-hopkins** [comment]
Looking at the code, you should be able to do the following, correct?

    $this->repo->findWhere(['columnName','>','10']);

**Comment by andersao** [comment]
@michael-hopkins Oops , my fault , had not implemented it. Released a version that supports this.

```php
$this->repo->findWhere([ ['columnName','>','10'], 'anotherField'=>'equals' ]); 
```

**Comment by michael-hopkins** [comment]
neat. seems simple enough :-)

**Comment by andersao** [comment]
;) :+1:

**Comment by michael-hopkins** [comment]
@andersao I was going to make the PR, but when I went into the look at the code, I was a little unsure where to put this (in addition to the docblock typehinting). But on the findWhere, `if(count($result) == 1)` should append a ->first() onto the end

**Comment by andersao** [comment]
@michael-hopkins The findWhere method did not help you?

**Comment by michael-hopkins** [comment]
ah nevermind. all good :-)
