### ISSUE TITLE
how to orderby collections? 

### ISSUE THREAD

**Issue by Gurzhii** [andersao/l5-repository#161]
can i order result without scopeQuery?
smth like
` $dictionary = $this->dictionary_repo->orderBy('title', 'desc')->all();`

**Comment by mgralikowski** [comment]
Same question here. How can i sort results? Example:
```
$this->testRepository->orderBy('column', 'direct')
            ->whereBetween('date', 'date'2);
```
How make it works? (No "order by" is added to query).
