### ISSUE TITLE
Where bind interface?

### ISSUE THREAD

**Issue by ssheduardo** [andersao/l5-repository#166]
One question, where bind interface?
In the example:

```
When running the command, you will be creating the "Entities" folder and "Repositories" inside the folder that you set as the default.
Done, done that just now you do bind its interface for your real repository, for example in your own Repositories Service Provider.

App::bind('{YOUR_NAMESPACE}Repositories\PostRepository', '{YOUR_NAMESPACE}Repositories\PostRepositoryEloquent');
```
What I must add that line file?
In AppServiceProvider.php?
Thanks.

**Comment by ionut-tanasa** [comment]
Hi,

I usually do this:

Create a new Provider calling it RepositoryProvider


```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class RepositoryProvider extends ServiceProvider
{

    private $bindings = [
        // interface => implementation
       {YOUR_NAMESPACE}Repositories\PostRepository => {YOUR_NAMESPACE}Repositories\PostRepositoryEloquent
    ];


    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        foreach ($this->bindings as $interface => $implementation) {
            $this->app->register($interface, $implementation);
        }
    }
}
```

Add it in `app.php` in the **providers** array : `App\Providers\RepositoryProvider::class`

So when I create new repositories I just add them to the **$bindings** array

**Comment by ssheduardo** [comment]
Thanks for help me.
Why not add in README.?

**Comment by OaiVo** [comment]
I have an issue: Target [App\Repositories\**] is not instantiable while building [App\Http\Controllers\**].
Pls, add this config in README !!

**Comment by younus93** [comment]
Yes, Even had the similar issue Target [App\Repositories*] is not instantiable while building [App\Http\Controllers\*].
