### ISSUE TITLE
visible() is not working

### ISSUE THREAD

**Issue by maxi032** [andersao/l5-repository#168]
I get Call to undefined method Illuminate\Database\Query\Builder::setVisible()

What I need to do is: 

<pre>
$items = $this->repo->with(['relation'])->visible(['item_id','item_name']);
</pre>

**Comment by ionut-tanasa** [comment]
`$this->repo->with(['relation'])` return a `Illuminate\Database\Query\Builder` instance.

[setVisible](https://laravel.com/api/5.2/Illuminate/Database/Eloquent/Model.html#method_setVisible) is a method of Eloquent Model.

Currently you can call `visible` without including relations.
We'll improve it in future releases.
