### ISSUE TITLE
Add to BaseRepository the ability to dynamically hide/show fields

### ISSUE THREAD

**Issue by michael-hopkins** [andersao/l5-repository#17]
It seems to me that 95% of the time there is a set of fields on (nearly) every model that can be safely put in the `protected $hidden` array. The things on the front of my mind are fields like `created_at, updated_at, deleted_at, created_by, deleted_by, updated_by`. 

I found [this thread](http://forumsarchive.laravel.io/viewtopic.php?id=8268) discussing this idea for a more specific implementation. 

I think it would be a big value add to be able to set on each model a set of fields to hide on default that could also be overridable. Similar to how `withTrashed()` works in Eloquent

**Comment by andersao** [comment]
@michael-hopkins Added in version 2.0.4 ;)


Hiding attributes of the model

```php
$post = $this->repository->hidden(['country_id'])->find($id);
```

Showing only specific attributes of the model

```php
$post = $this->repository->visible(['id', 'state_id'])->find($id);
```

**Comment by michael-hopkins** [comment]
man, talk about customer service.

**Comment by DesmondPang** [comment]
Hidden and visible functions are not working. I am using "prettus/l5-repository": "^2.1",
