### ISSUE TITLE
Single function to Create with Many to Many Relationship.

### ISSUE THREAD

**Issue by Mahmoudz** [andersao/l5-repository#170]
First thank you for this great package :+1: 

I have a many to many relationship between `Accounts` and `Tags`.

And I have this simple Account data structure (with the tags IDs and the user_id).

```shell
array:6 [
  "url" => "www.github.com"
  "username" => "mega@mail.dev"
  "secret" => "I_am_the.secret#123"
  "tags" => array:3 [
    0 => 1
    1 => 2
    2 => 3
  ]
  "user_id" => "1"
]
```

If I try to pass all this data to the `create` function. I get the Account created but will NOT save the data on the Pivot table. would be nice if it hane handle this but I understand why it cannot.
```php
$account = $accountRepository->create($data);
```
Moreover for me it's unsafe to pass the user_id (relationship) with the data. Since this allows passing wrong ID's. unlike the `$account->user()->associate($this->user);` which throws an error when User ID not found.

<br>

However the alternative that I currently follow_(shown in the code below)_, is to create an account object set the data and some relationships on it and then convert it into an array and pass it to the create function.

**But the problem here** is with the `Many To Many` relationship, since it cannot be set before the model is already created in the Database _(the `attach` function requires the Account ID to save it on the pivot table)_. For that I need to `create` and then `attach` the `Many To Many` relationship and then use the `update` repository function like so:

```php
        $account = new Account();

        $account->url = $this->url;
        $account->username = $this->username;
        $account->secret = $this->secret;

        $account->user()->associate($this->user);

        $account = $accountRepository->create($account->toArray());
        
        if ($this->tags) {
            $account->tags()->attach($this->tags);
            
            $account = $accountRepository->update($account->toArray(), $account->id);
        }
```

Was wondering if you create a function `createWithMany` that automates the creation of Many to Many, here's an example of the usage and implementation:

Usage:
```php
        $accountRepository->createWithMany($account->toArray(), [
            'tags' => $this->tags,
        ]);
```
Sample Implementation:
```php
    public function createWithMany(array $attributes, array $manyToManyRelation)
    {
        $model = $this->create($attributes);

        foreach ($manyToManyRelation as $key => $values) {

            if ($values) {
                $model->{$key}()->attach($values);

                $model = $this->update($model->toArray(), $model->id);
            }

        }

        return $model;
    }
```

> One more thing: would prefer to pass the $account as object and the `create/update` function detects it and then convert it into an array.

**Comment by mrgrain** [comment]
I think this is a very common problem, but I am not sure if it is one that can (and should) be solved generally. The main issue I've got with your `createWithMany()` method is the skipping of validation for the relations. That pushes responsibility for validation back to the controller, which is exactly the opposite of what a Repository is for.

We've a similar setup and what we do is that we simple overwrite the `create()` method within our `AccountRepository`. Tags will be pushed through the `AccountValidator` first. This works very well and is straight forward code in the controller. (The downside for you would be that you'll have to inject the tags into to attributes array, since they're apparently not user input.)

Controller:
```php
$accountRepository->create($account->toArray() + ['tags' => $this->tags]);
```
Repository:

```php
   public function create(array $attributes)
    {
        $tags = array_get($attributes, 'tags', []);

        // Have to skip presenter to get a model not some data 
        $temporarySkipPresenter = $this->skipPresenter;
        $this->skipPresenter(true);
        $model = parent::create($attributes);
        $this->skipPresenter($temporarySkipPresenter);

        // attach tags
        foreach ($tags as $key => $values) {
            $model->tags()->attach($values);
        }
        $model->save();

        return $this->parserResult($model);
    }
```

**Comment by mauro-gallo** [comment]
Good Morning, thank you @mrgrain, i I followed your advice and I get the desired result.

In the controller I would like to return the model with the tags in json format. Without the package i write:

`return $this->model->with('tags')->toJson();`

i want to use the presenter/transformer. Can you help me?

best regards

**Comment by mrgrain** [comment]
@mauro-gallo  Puh, it has been a while, but I'll give it a shot. 😆 

The `create` method of a repository (or any method for that matter), should still return a model. So I'd expect you can do something like this:
`return $repository->create($data)->with('tags')->toJson();`

Alternatively you might have change your repository method to include the relation:
`return $this->parserResult($model->with('tags'));`
