### ISSUE TITLE
Not Creating a Controller.

### ISSUE THREAD

**Issue by GiovanniValen** [andersao/l5-repository#174]
Hey, I am trying out this method in my laravel project but when doing "php artisan make:entity Cats... ", it is not creating a Controller for Cats. I am using laravel 5.2.26

**Comment by mvpasarel** [comment]
What error do you have? Are you using develop branch or master?

**Comment by GiovanniValen** [comment]
I used composer to install prettus.

1. When putting the RepositoriesSericeProvider in the Register class in AppServiceProvider. It states that it's not found. Even after using php artisan vendor:publish.

2. When making a entity it's not making a Controller for the CRUD resource.

On Apr 12, 2016, at 10:36 AM, Madalin Pasarel <notifications@github.com<mailto:notifications@github.com>> wrote:

What error do you have? Are you using develop branch or master?
On Apr 12, 2016 5:32 PM, "Gio" <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hey, I am trying out this method in my laravel project but when doing "php
> artisan make:entity Cats... ", it is not creating a Controller for Cats. I
> am using laravel 5.2.26
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/andersao/l5-repository/issues/174>
>

-
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/andersao/l5-repository/issues/174#issuecomment-208936721>

Please Note: Due to Florida's very broad public records law, most written communications to or from College employees regarding College business are public records, available to the public and media upon request. Therefore, this email communication may be subject to public disclosure. This message is the property of Hillsborough Community College or its affiliates. It may be legally privileged and/or confidential and is intended only for the use of the addressee(s). No addressee should forward, print, copy, or otherwise reproduce this message in any manner that would allow it to be viewed by any individual not originally listed as a recipient. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is strictly prohibited. If you have received this communication in error, please immediately notify the sender and delete this message. Thank you. Please Note: Due to Florida's very broad public records law, most written communications to or from College employees regarding College business are public records, available to the public and media upon request. Therefore, this email communication may be subject to public disclosure. This message is the property of Hillsborough Community College or its affiliates. It may be legally privileged and/or confidential and is intended only for the use of the addressee(s). No addressee should forward, print, copy, or otherwise reproduce this message in any manner that would allow it to be viewed by any individual not originally listed as a recipient. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is strictly prohibited. If you have received this communication in error, please immediately notify the sender and delete this message. Thank you.

**Comment by ionut-tanasa** [comment]
@GiovanniValen it's not yet released.

**Comment by GiovanniValen** [comment]
Oh okay


On Apr 12, 2016, at 10:46 AM, Ionut Tanasa <notifications@github.com<mailto:notifications@github.com>> wrote:


@GiovanniValen<https://github.com/GiovanniValen> it's not yet released.

-
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/andersao/l5-repository/issues/174#issuecomment-208941881>

Please Note: Due to Florida's very broad public records law, most written communications to or from College employees regarding College business are public records, available to the public and media upon request. Therefore, this email communication may be subject to public disclosure. This message is the property of Hillsborough Community College or its affiliates. It may be legally privileged and/or confidential and is intended only for the use of the addressee(s). No addressee should forward, print, copy, or otherwise reproduce this message in any manner that would allow it to be viewed by any individual not originally listed as a recipient. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is strictly prohibited. If you have received this communication in error, please immediately notify the sender and delete this message. Thank you. Please Note: Due to Florida's very broad public records law, most written communications to or from College employees regarding College business are public records, available to the public and media upon request. Therefore, this email communication may be subject to public disclosure. This message is the property of Hillsborough Community College or its affiliates. It may be legally privileged and/or confidential and is intended only for the use of the addressee(s). No addressee should forward, print, copy, or otherwise reproduce this message in any manner that would allow it to be viewed by any individual not originally listed as a recipient. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is strictly prohibited. If you have received this communication in error, please immediately notify the sender and delete this message. Thank you.
