### ISSUE TITLE
Serialization of 'Closure' is not allowed using l5-repository

### ISSUE THREAD

**Issue by humayunghani** [andersao/l5-repository#175]
I'm unable to pass a repository to my event handler only when it implements ShouldQueue. Please note that it works fine when I don't pass repository. The error which it throws is "Serialization of 'Closure' is not allowed". Is there anything I'm doing wrong?

Here's my "UserRegistered" event where I'm passing a repository...
```
<?php
namespace App\Users\Events;

use App\Events\Event;
use App\Contracts\UserRepository;

class UserRegistered extends Event
{
    public $userid;

    public $userRepo;

    public function __construct(UserRepository $userRepo, $userid)
    {
		$this->userRepo = $userRepo;
		$this->userid   = $userid;
    }
}
```

And this is my listener...
```
<?php namespace App\Users\Listeners;

use App\Users\Events\UserRegistered;
use Illuminate\Contracts\Queue\ShouldQueue;

class UserRegisteredEventListener implements ShouldQueue
{
    public function __construct()
    {
        //
    }

    public function handle(UserRegistered $event)
    {
        \Log::info("Do any necessary work when a userRegistered.\n", ["User" => $event->userRepo->find($event->userid), 
            "Userid" => $event->userid]);
    }
}
```
My UserRepository implementation is UserRepositoryEloquent.

So it's throwing error unless I remove "implements ShouldQueue" from the UserRegisteredEventListener. Can anyone help me out? Thanks.

**Comment by mvpasarel** [comment]
@humayunghani There is no way to fix this.

However, you can always do the repository basic queries in the Event class and send to the Listener some array data so you can "do any necessary work when a userRegistered" which can be more complex.

**Comment by humayunghani** [comment]
yeah I just realized that since repository doesn't hold any data so why would i want to pass it anyway? The real stuff which we need is the relevant data itself. Thanks for your help, I really appreciate it.
