### ISSUE TITLE
Generators not working with Lumen

### ISSUE THREAD

**Issue by mrgrain** [andersao/l5-repository#179]
The generators are not working with Lumen. There are several issues:

1. `Fatal error: Call to undefined function Prettus\Repository\Generators\app_path() in Prettus\Repository\Generators\PresenterGenerator.php on line 77`
`app_path()` is a Laravel only function. If you need to use it, you can ship it in your helper.php

2. `Call to undefined method Laravel\Lumen\Application::getNamespace() in illuminate\console\AppNamespaceDetectorTrait.php on line 16`
`Lumen\Application` doesn't have the `getNamespace()` method. We need to detect the namespace otherwise.

3. `Class 'File' not found in prettus\l5-repository\src\Prettus\Repository\Generators\Commands\PresenterCommand.php on line 51`
Not a Lumen thing either.

4. `make:request` command is not available in Lumen

5. `make:provider` command is not available in Lumen

I might have time to create a PR for fixing the first 3 issues. Not sure on how to handle 5 & 6 though, as I am not 100% why and if they are needed. Maybe we can just skip them with Lumen, as they are not used in Lumen anyway.

**Comment by ionut-tanasa** [comment]
Actually this is my fault. 
Will release a new version ASAP. Removing the commands from the service provider. 


But we definetly should add generators for lumen too.

**Comment by ionut-tanasa** [comment]
Closing 45d61fa
