### ISSUE TITLE
Recommendation on using with multitenant package?

### ISSUE THREAD

**Issue by michaeljhopkins** [andersao/l5-repository#18]
I am using a forked version of [this](https://github.com/AuraEQ/laravel-multi-tenant) repository to implement multitenant. This means my models have `use TenantScopedModelTrait` on them. In this trait there is the following eloquent override. 

    /**
     * Override the default findOrFail method so that we can rethrow a more useful exception.
     * Otherwise it can be very confusing why queries don't work because of tenant scoping issues.
     *
     * @param       $id
     * @param array $columns
     *
     * @throws TenantModelNotFoundException
     */
    public static function findOrFail($id, $columns = ['*'])
    {
        try {
            return parent::query()->findOrFail($id, $columns);
        } catch (ModelNotFoundException $e) {
            throw with(new TenantModelNotFoundException())->setModel(get_called_class());
        }
    }

The BaseRepository of course does not have this method, so running the code below results in the two different errors represented

    $id = 2500 //An order ID that does not exist in my current `orders` table

	// Exception message = "No query results for model [Hello\Orders\Order] when scoped by tenant."
	$TenantModelNotFoundException = Order::findOrFail($id);

	// Exception message = "Call to undefined method Hello\Orders\Repositories\OrderRepository::findOrFail()"
	$FatalErrorException = $this->order->findOrFail($id);

I'm wondering what you believe the best way for me to resolve this would be. Should I extend BaseRepository and add a findOrFail() method?

**Comment by andersao** [comment]
@michael-hopkins First excuse me for the delay in responding. I am very busy these days

I'll do some tests and give you some solution soon;)

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by ionut-tanasa** [comment]
`$FatalErrorException = $this->order->findOrFail($id);`

There is no findOrFail method on the BaseRepository. There's **find()** though. Which internally calls **findOrFail()**

Using your Trait but calling `$this->order->find($id); `instead of `$this->order->findOrFail($id);` should work.
