### ISSUE TITLE
Bad gateway...

### ISSUE THREAD

**Issue by kylescousin** [andersao/l5-repository#180]
Hey, I'm trying to inject a repository in the controller and I get '502 bad gateway'. When I don't inject it, the error is gone. What am I overlooking here?

Code: http://laravel.io/bin/7w4av

**Comment by ionut-tanasa** [comment]
The is actually ok. 

502 error maybe it's a server config error.

Can you provide the stack trace ?

**Comment by kylescousin** [comment]
@ionut-tanasa The error shows only 502 bad gateway without a stack trace.
And also laravel.log is empty...

Where can I find the details of the error?

**Comment by ionut-tanasa** [comment]
So it's a web server issue.

Check NGINX / APACHE error logs

**Comment by kylescousin** [comment]
This is what it says:

2016/04/18 13:52:08 [error] 2309#2309: *123 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.1, server: vw.local, request: "GET /play HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "vw.local"
