### ISSUE TITLE
Dependency of laravel helpers by using `request` method

### ISSUE THREAD

**Issue by catalinux** [andersao/l5-repository#183]
I  see that https://github.com/andersao/l5-repository/blob/3fb2cb778edcad84c3904bd8a26a6fc843cf83d9/src/Prettus/Repository/Eloquent/BaseRepository.php#L325 there is a depenecy of `request` helper  which is not defined in Lumen for example.

Why is such dependency? The lifecycle should be:
HTTP Request => Controller => Repostory::paginate() 

In controller we should parse the request input (ie: `perPage` key) and pass it to the `paginate` method

**Comment by motamonteiro** [comment]
I´m having the same problem, 
How to use the paginate method on Lumen?

Fatal error: Call to undefined function Prettus\Repository\Eloquent\request() in D:\web\api\PHP\Itcmd\vendor\prettus\l5-repository\src\Prettus\Repository\Eloquent\BaseRepository.php on line 325

**Comment by edmundluong** [comment]
Hey @ionut-tanasa,

I see your fix for this in  https://github.com/andersao/l5-repository/commit/e67ad08cd79976c10463ec24d21d6b3587e5aa4b but it looks like you missed another dependency on the request() method here https://github.com/andersao/l5-repository/commit/e67ad08cd79976c10463ec24d21d6b3587e5aa4b#diff-b8ab2527e21391a4920b7bbedf00e099R329 .

This is still failing for me on v2.6.2, I'll see if I can find a workaround
