### ISSUE TITLE
fieldSearchable with criteria join returning ambiguous error

### ISSUE THREAD

**Issue by fndmiranda** [andersao/l5-repository#184]
fieldSearchable with criteria and join is returning ambiguous error and when it passes the 'farm_farms.name' => 'like' in $fieldSearchable on repository returns error Call to undefined method Illuminate\Database\Query\Builder::farm_farms()

**Comment by msamec** [comment]
Do you have to relation setup for the model you are trying to search?

**Comment by fndmiranda** [comment]
Actually the problem is that when I do a search ambiguous error in the query because of the join criteria

**Comment by humayunghani** [comment]
How do you make joins with criteria? Can anybody help me on this, any links? I'm stuck right now.

**Comment by ionut-tanasa** [comment]
I think I got why you get this error.
You are joining with the same column names.
If in the result set you get two equal names it will throw that error. 

you should give aliases to your joins / columns to make them unique.
