### ISSUE TITLE
bug: criteria is ignored

### ISSUE THREAD

**Issue by amin101** [andersao/l5-repository#191]
I have noticed if i use `where` clause in a statement then `pushCriteria()` method will be ignored.

```php
 $this->postRepository->pushCriteria(new PostBookCheckConfirm());
       
        $post = $this->postRepository
            ->where('slug', $slug)
            ->with(['tagged', 'comments'])
            ->first();
```
and this is criteria `apply` method:
```php
 public function apply($model, RepositoryInterface $repository)
    {
        $model = $model->where(function($q){
            $q->where('confirm',1);
        });

        return $model;
    }
```
 this code is part of controller show method. using `where('slug', $slug)` would inactive applying `pushCriteria` , of course if i remove `where` then criteria works fine

**Comment by amin101** [comment]
Oh,seems it was my fault. i was added a trait with a `where` function. for it to work correctly it should be so:
```php
    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {

        $this->model = $this->model->where($column, $operator, $value, $boolean);

        return $this;
    }
```
But still i don't know  why there is no `where` clause defined in baserepository.

**Comment by pjmartorell** [comment]
@amin101 the equivalent method that you are looking for is `findWhere`. Check the documentation of l5-repository for futher details. You don't need to create a `where` method for this purpose.
