### ISSUE TITLE
Help to make a search by 2 parameters

### ISSUE THREAD

**Issue by diego-goulart** [andersao/l5-repository#206]
I want to make a request search using 2 parameters to make a search like this:
`select * from `your_table` where `sap` like '%VALUE%' and `team_id` = 'VALUE';`

This is the request that ive make:
`http://crm.app/member?search=sap:6337,team_id:1`

But the request above produces a query like:
`select * from `your_table` where `sap` like '%VALUE%' OR `team_id` = 'VALUE';`

How to make a request that produces a query using "**AND**" but not "**OR**"?

**Comment by hisway** [comment]
In 

> vendor\prettus\l5-repository\src\Prettus\Repository\Criteria\RequestCriteria.php

 

> apply()

 `$modelForceAndWhere = false` => `$modelForceAndWhere = true`

**Comment by shez1983** [comment]
this is not correct  - imean you are telling us to modify core files which will be overwritten by any new updates - also a problem arises when you  modify and upload your project a vendor files are not in git repo, you may find things going wrong & forget all these modifications - which you need to keep up with
