### ISSUE TITLE
updateOrCreate

### ISSUE THREAD

**Issue by ramonsy** [andersao/l5-repository#210]
Prettus\Repository\Eloquent\BaseRepository
Line 529

`        if (!is_null($this->validator)) {
            $this->validator->with($attributes)->passesOrFail(ValidatorInterface::RULE_UPDATE);
        }`

Should be

`        if (!is_null($this->validator)) {
            $this->validator->with($values)->passesOrFail(ValidatorInterface::RULE_UPDATE);
        }`

**Comment by joaorobertopb** [comment]
@ionut-tanasa validation should be performed with the data to be stored in the DB ($values) and not with the data that form the condition where ( $attributes ) 

?
