### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by mrbarde** [andersao/l5-repository#216]
Please i have never successfully used this package on a project even tho i like the coding workflow it helps create, the same problem as i have always seen is your documentation, it is poor and unclear on vital parts of your package, for example the repository service provider, in the config file of this package appears useless seeing that one would have already registered the service provider in the `app -> config.php` file at installation, if this has a separate function, please make it clear in your documentation, a lot of people will be using your package, and will lose a lot of work hours trying to figure out things you didn't document clearly, no matter how simple it may seem to actually be, if it is important document it, there is no such thing as too much documentation, currently i have lost three hours in my work time trying to figure out how to get past the provider issue when I run `php artisan make:entity Post` from command prompt, it's gotten me tired and exhausted. That being said i still think this is a great package for creating and handling repositories, you just have to make the documentation a lot more clear, thanks!

**Comment by mvpasarel** [comment]
@mrbarde Feel free to make a pull request and update the documentation as you would like to found it. I agree with you, you must not let others lose their time as you did.
