### ISSUE TITLE
How to add new methods?

### ISSUE THREAD

**Issue by ssheduardo** [andersao/l5-repository#218]
Hi, 
I have a questions, how to add a new method (What file modify?)
For example:

    public function deleteMultipleById(array $ids)
    {
        return $this->model->destroy($ids);
    }

Where add the code?
`vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php` or
`Repositories/CustomRepository.php`

**Comment by uar-madalin-pasarel** [comment]
@ssheduardo You should not *ever* modifiy vendor/ files. Just create a new CustomRepository class in your Repositories/ folder and extend it in your repositories instead of BaseRepository.

**Comment by mvpasarel** [comment]
@ssheduardo You should not ever modifiy vendor/ files. Just create a new CustomRepository class in your Repositories/ folder and extend it in your repositories instead of BaseRepository.

**Comment by ssheduardo** [comment]
@mvpasarel for default when create a repository with command
`php artisan make:repository CompanyType`

Create 2 files:
`Repositories/CompanyTypeRepository.php` and
`Repositories/CompanyTypeRepositoryEloquent.php`

So, add the new method in?
`CompanyTypeRepositoryEloquent.php`

```
public function deleteMultipleById(array $ids)
{
    return $this->model->destroy($ids);
}
```

**Comment by mvpasarel** [comment]
There is no reason in adding that method in all the Eloquent Repositories. Create a new class in your Repositories/ folders


    class Custom Repository extends BaseRepository {
        public function deleteMultipleById(array $ids)
        {
            return $this->model->destroy($ids);
        }
    }


And in the generated files you will need to have:

     CompanyTypeRepositoryEloquent extends CustomRepository


Makes sense?

**Comment by ssheduardo** [comment]
Thanks @mvpasarel  for help me.
Why not @andersao add more documentacion and examples over your repository?.

**Comment by mvpasarel** [comment]
@ssheduardo Your question is about OOP in PHP, not package related. 

As you can imagine, @andersao and all the other contributors have full-time jobs and everybody did as much as they could. 

Feel free to make pull requests with what you think is missing from the documentation.

**Comment by ssheduardo** [comment]
@mvpasarel I understand that all contribute to the code in their little free time.
This repository is great, thanks a all people.

**Comment by malyusha** [comment]
@mvpasarel What if I decide to create something like CompanyTypeRepositoryRedis later? Wouldn't it be better to create new methods in CompanyTypeRepository interface to force all repositories types implement them? So, in case of `deleteMultipleById` it will be like:
```
interface CompanyTypeRepository()
{
    public function deleteMultipleById();
}

class CompanyTypeRepositoryEloquent extends BaseRepository implements CompanyTypeRepository
{
    public function deleteMultipleById($ids)
    {
        return $this->model->destroy($ids);
    }
}

class CompanyTypeRepositoryRedis implements CompanyTypeRepository
{
    public function deleteMultipleById($ids)
    {
        //Do stuff to delete all via redis
    }
}
```

**Comment by mvpasarel** [comment]
@malyusha Looks good to me.

**Comment by ssheduardo** [comment]
@malyusha good idea.
Thanks...
