### ISSUE TITLE
Change $modelForceAndWhere value

### ISSUE THREAD

**Issue by tibi00** [andersao/l5-repository#219]
Hi!

Please I would like to use the RequestCriteria with AND condition on all seach parameters. I've found a variable `$modelForceAndWhere` in the `RequestCriteria`, which does exactly what I want, but it has a fix `false` value. Thanks!

**Comment by mvpasarel** [comment]
@tibi00 I have created a new Critera, extended RequestCriteria and overridden the `apply` method just to make `$modelForceAndWhere=true`. Try that and it will work.

**Comment by tibi00** [comment]
@mvpasarel Thank you, I dit it earlier, but the original `RequestCriteria` changed over the time, got new features, and I had to update the derived class every time. That is why I thought it would be a good feature to configure the original one.

**Comment by cdarken** [comment]
@mvpasarel how did you override it? it's a local variable in RequestCriteria::apply

**Comment by mvpasarel** [comment]
You wont guess it :) Check line 41.

https://gist.github.com/mvpasarel/cbb09fef317116d78b202db86be85bed

And I use it in my controllers like this:

`$this->repository->pushCriteria(app('App\Criteria\BaseCriteria'));`

**Comment by cdarken** [comment]
Yeah, that is not really overriding the variable, you've overridden the entire method. I think the method in the last comment of issue #102  is better

**Comment by mvpasarel** [comment]
@cdarken That's what I said in my original comment, that I am overriding the `apply` method. Use any solution you like
