### ISSUE TITLE
using repository create method fails when attribute is marked as hidden & fillable

### ISSUE THREAD

**Issue by computerfr33k** [andersao/l5-repository#225]
I have a user object that I am trying to create using
```php
$this->userRepository->create([
    'name' => 'user1',
]);
```
and the User object has the password field marked as hidden, but also fillable.
but once I use the create method, it fails saying that the password field is required even though it passes validation before being passed to the repository method.

**Comment by mvpasarel** [comment]
@computerfr33k What's your repository and user validator code?

**Comment by computerfr33k** [comment]
Repository:
```php
<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Entities\User;
use App\Validators\UserValidator;

/**
 * Class UserRepositoryEloquent.
 */
class UserRepositoryEloquent extends BaseRepository implements UserRepository
{
    /**
     * Specify Model class name.
     *
     * @return string
     */
    public function model()
    {
        return User::class;
    }

    /**
     * Specify Validator class name.
     *
     * @return mixed
     */
    public function validator()
    {
        return UserValidator::class;
    }

    /**
     * Boot up the repository, pushing criteria.
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}

```

UserValidator:
```php
<?php

namespace App\Validators;

use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\LaravelValidator;

class UserValidator extends LaravelValidator
{
    protected $rules = [
        ValidatorInterface::RULE_CREATE => [
            'first_name' => 'required|max:255',
            'last_name' => 'required|max:255',
            'email' => 'required|email|unique:users|max:255',
            'phone_number' => 'required|numeric|unique:users|digits_between:10,14',
            'password' => 'required|min:6',
            'user_name' => 'required|unique:users|max:255',
        ],
        ValidatorInterface::RULE_UPDATE => [
            'first_name' => 'max:255',
            'last_name' => 'max:255',
            'email' => 'email|unique:users|max:255',
            'phone_number' => 'numeric|unique:users|digits_between:10,14',
            'user_name' => 'unique:users|max:255',
        ],
   ];
}

```

```php
try {
            $temp = factory(User::class)->make(['password' => 'myPassword'])->makeVisible(['password'])->toArray();

            $this->validator->with($temp)->passesOrFail(ValidatorInterface::RULE_CREATE);

            $user = $this->userRepository->create($temp);

            $response = [
                'message' => 'User created.',
                'data'    => $user->toArray(),
            ];

            if ($this->request->wantsJson()) {
                return response()->json($response);
            }

        } catch (ValidatorException $e) {
            if ($this->request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag(),
                ]);
            }
        }
```

**Comment by mvpasarel** [comment]
At least for your initial code, it will fail as you are sending only `name` in your array:

    
    $this->userRepository->create([
        'name' => 'user1',
    ])


The validation rule for repository `create` method is in `ValidatorInterface::RULE_CREATE` array and it says `password:required`.

**Comment by computerfr33k** [comment]
I am passing in an array from the faker factory and made the password visible. But from my first post I did say that it does pass the validator, but the problem is that the factory create is making the model and then passing the array and recasting back to an array causing the password field to be re hidden failing the validation.
On 17 Jun 2016 2:00 PM, Madalin Pasarel <notifications@github.com> wrote:At least for your initial code, it will fail as you are sending only name in your array:

$this->userRepository->create([
    'name' => 'user1',
])


The validation rule for repository create method is in ValidatorInterface::RULE_CREATE array and it says password:required.

**Comment by computerfr33k** [comment]
here's the problematic line which doesn't allow an attribute to be fillable and hidden using the create method.
https://github.com/andersao/l5-repository/blob/master/src/Prettus/Repository/Eloquent/BaseRepository.php#L464

**Comment by damian-nz** [comment]
I have just submitted [this PR](https://github.com/andersao/l5-repository/pull/255) to fix this issue

**Comment by zjien** [comment]
same problem but @damian-nz 's code fixed it

**Comment by zjien** [comment]
can I solve it by this way?
remove: `$attributes = $this->model->newInstance()->forceFill($attributes)->toArray();`

**Comment by tucq88** [comment]
This should not be closed when it's not merged to master yet :(

**Comment by ecuation** [comment]
Does it already fixed?? I have the same issue with it. How do they solved?

Thanks in advance.

**Comment by andre-bahia** [comment]
I also have the same problem!

**Comment by tdchien** [comment]
I still got this problem on Laravel 5.1 with error message "Call to undefined method Illuminate\Database\Query\Builder::makeVisible()"
