### ISSUE TITLE
Max() in ScopeQuery

### ISSUE THREAD

**Issue by andressabarelli** [andersao/l5-repository#234]
I´m trying to use a scopeQuery for the max() in a field. How should I do?

If I use the code below, the all() function doesn´t work, because the return is only an integer. So I should use that function in its place?

```
public function maxID()
{
    return $this->scopeQuery(function($query){
        return $query->max('IDCompany');
    })->all();
}
```

**Comment by joaosalless** [comment]
This solve the problem?

```php
public function maxID()
{
    return $this->model->max('IDCompany');
}
```
