### ISSUE TITLE
How to get next page ? Using paginate

### ISSUE THREAD

**Issue by liubusian** [andersao/l5-repository#235]
When using the method "paginate", how to set `$page`???
in Illuminate\Database\Eloquent\Builder
`public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)`

but in Prettus\Repository\Eloquent\BaseRepository
```
public function paginate($limit = null, $columns = ['*'], $method = "paginate") {
   ....................
         $results = $this->model->{$method}($limit, $columns);
```
Only use `$limit, $columns`
I can't set `$page` when using prettus's paginate..

Some people have the same problem?

Or hava a good idea to solve?

Thanks

**Comment by mvpasarel** [comment]
@liubusian It's the same as you do it with pure Laravel. Use `page` input in your request query.

    http://localhost/users?page=2

And the magic is done under the hood.

**Comment by liubusian** [comment]
OK, I find it.
At `Illuminate\Pagination\AbstractPaginator` line:326
```
public static function resolveCurrentPage($pageName = 'page', $default = 1)
    {
        if (isset(static::$currentPageResolver)) {
            return call_user_func(static::$currentPageResolver, $pageName);
        }

        return $default;
    }
```
solved

Thanks.
