### ISSUE TITLE
transformers defaultInclude not working

### ISSUE THREAD

**Issue by devmark** [andersao/l5-repository#24]
~~~~
class BookTransformer extends TransformerAbstract
{
    protected $defaultIncludes = [
        'author'
    ];
   ...
    public function includeAuthor(Book $book)
    {
        $author = $book->author;

        return $this->item($author, new AuthorTransformer);
    }
}
~~~~
- already using with(['author'])
- $book->author will return null

**Comment by jonagoldman** [comment]
Hey @devmark I am trying to do a similar thing. I basically want to decide when to transform relationships. Would appriciate your help.

Please take a loot at the issue I opened here: #101

Thanks.
