### ISSUE TITLE
Add blank line after doc block description 

### ISSUE THREAD

**Issue by Lisennk** [andersao/l5-repository#240]
How it looks now:

```
/**
 * Interface SendingRepository
 * @package namespace App\Repositories;
 */
```

But if you create package for Lravel 5, it must follow guidelines and be like in Laravel 5 files:

```
/**
 * Interface SendingRepository
 *
 * @package namespace App\Repositories;
 */
```

Yeah, im boring as fuck

**Comment by danmurf** [comment]
I'll dig through and update :)

**Comment by danmurf** [comment]
Added these in pull request [295](https://github.com/andersao/l5-repository/pull/295)
