### ISSUE TITLE
repository->paginate() returns an array

### ISSUE THREAD

**Issue by godcong** [andersao/l5-repository#241]
when i use Presenter in Eloquent
the repository->paginate did not return an LengthAwarePaginator object

only return an array

so , i can't use render() in blade templete

**Comment by 42antoine** [comment]
My solution, with some LengthAwarePaginator tips based on this article : http://blog.mauriziobonani.com/laravel-keep-url-query-parameters-in-manual-pagination/

```

{{ with(

			new \Illuminate\Pagination\BootstrapThreePresenter(
				new \Illuminate\Pagination\LengthAwarePaginator(
					$items['meta']['pagination']['count'],
					$items['meta']['pagination']['total'],
					$items['meta']['pagination']['current_page'],
					$items['meta']['pagination']['per_page']
					[
						'path' => Request::url(),
						'query' => Request::query(),
					]
				)
			)

)->render() }}

```

**Comment by quynhbkit** [comment]
You can try like this:

`
$this->repository->skipPresenter(true)->paginate(...)
`

**Comment by 42antoine** [comment]
For laravel 5.3

```php
function pagination($nb_rows, $total_row, $current_page, $per_page = 15)
{
	$paginator = new \Illuminate\Pagination\LengthAwarePaginator(
		$nb_rows,
		$total_row,
		$per_page,
		$current_page,
		[
			'path' => Request::url(),
			'query' => Request::query(),
		]
	);

	return $paginator->render('partials.common.pagination');
}
```

**Comment by godcong** [comment]
public static function arrayPaginate($result, $paginate = 15)
    {
        $pageName = 'page';
        $page = Paginator::resolveCurrentPage($pageName);
        $total = count($result);
        return new LengthAwarePaginator($result, $total, $paginate, $page, [
            'path' => Paginator::resolveCurrentPath(),
            'pageName' => $pageName,
        ]);
    }

**Comment by jgardezi** [comment]
@godcong can you please explain more about your solution i.e. where we have to add the following function 

`
public static function arrayPaginate($result, $paginate = 15)
{
    $pageName = 'page';
    $page = Paginator::resolveCurrentPage($pageName);
    $total = count($result);
    return new LengthAwarePaginator($result, $total, $paginate, $page, [
        'path' => Paginator::resolveCurrentPath(),
        'pageName' => $pageName,
    ]);
}
`
