### ISSUE TITLE
Problem using method deleteWhere

### ISSUE THREAD

**Issue by eullercristian** [andersao/l5-repository#242]
Dear, 

I have the code bellow

`$this->repoPagamento->deleteWhere(['recibo_id' => $recibo]);`

When i use this method deleteWhere, i have the issue

 `Argument 2 passed to PrettusRepositoryEventsRepositoryEventBase::__construct() must be an instance of IlluminateDatabaseEloquentModel, instance of IlluminateDatabaseEloquentBuilder given, called in PrettusRepositoryEloquentBaseRepository.php on line 587`

Its a issue using this method deleteWhere?

**Comment by joaosalless** [comment]
I have the same problem.

```
FatalThrowableError in RepositoryEventBase.php line 32:

Type error: Argument 2 passed to Prettus\Repository\Events\RepositoryEventBase::__construct() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Database\Eloquent\Builder given, called in /home/joao/Projetos/myproject/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php on line 587
```

**Comment by joaosalless** [comment]
I think this solves the problem:

In the file `/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php` line `587`

change
```php
...
event(new RepositoryEntityDeleted($this, $this->model));
...
```
to
```php
...
event(new RepositoryEntityDeleted($this, $this->model->getModel()));
...
```

For me, it worked

**Comment by eullercristian** [comment]
@joaosalless send a pr for @andersao. @andersao Can you take a look in this issue?

Thanks a lot!
