### ISSUE TITLE
How to use chunk() in repository?

### ISSUE THREAD

**Issue by Overx** [andersao/l5-repository#244]
How to use method chunk() in repository? Thx

**Comment by devingray** [comment]
@Overx Did you ever find out how to do this?

**Comment by marcus13371337** [comment]
I extended the BaseRepository with the following in order to get this to work:
`    public function chunk($limit, callable $callback)
    {
        $this->applyCriteria();
        $this->applyScope();

        if($this->model instanceof Illuminate\Database\Eloquent\Builder) {
            $modelQuery = $this->model->getQuery();
        } else {
            $modelQuery = $this->model;
        }
        
        $underlyingQueryBuilder = $modelQuery->getQuery();
        if (empty($underlyingQueryBuilder->orders) && empty($underlyingQueryBuilder->unionOrders)) {
            $this->model->orderBy($modelQuery->getModel()->getQualifiedKeyName(), 'asc');
        }
        
        $presenterFunction = \Closure::bind(function($results,$page) use (&$callback) {
            return $callback($this->parserResult($results), $page);
        }, $this);
    
        return $this->model->chunk($limit, $presenterFunction);
    }`
