### ISSUE TITLE
Use repository outside controller

### ISSUE THREAD

**Issue by kojilab** [andersao/l5-repository#248]
Hi,

How can I use the repository outside of a controller? I couldn't find it in the docs.

Thanks

**Comment by tianyong90** [comment]
@kojilab 
```php
$userRepo = app(\App\Repositories\UserRepository::class);
$user = $userRepo->find(1);

dump($user);
```
You can use it in this way, it works for me.

**Comment by kojilab** [comment]
Thanks a lot!!!!
