### ISSUE TITLE
Change result order

### ISSUE THREAD

**Issue by henninghorn** [andersao/l5-repository#25]
I'm trying to create a page which list items from newest to old.
I can easily do this by doing this in my repository's boot method: $this->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));

and adding ?orderBy=id&sortedBy=desc.

But I want it to do this by default.
So I push a custom criteria in my repository's boot method, but I end up getting "Undefined variable: query".

I have followed the documentation, but after re-checking etc. I still get the "undefined variable query"-message

What am I doing wrong?

**Comment by henninghorn** [comment]
So I did some research, and the documentation seems to be wrong.
Instead of using $query within the apply method of your criteria, you should use $model.

**Comment by andersao** [comment]
@henninghorn Thanks man, will update the documentation

**Comment by henninghorn** [comment]
Btw, glad to see that url request params overrides any criteria pushed within a controller or repository.
