### ISSUE TITLE
How to add a unique validation for table having custom primary key?

### ISSUE THREAD

**Issue by mhetreramesh** [andersao/l5-repository#250]
I was trying to add unique validation for the table having custom primary key.
In my case I have a table user with user_id as primary key & while applying unique validation I have to pass the value of he current item, how how can I do that?
`public static $rules = [`
        `'name' => 'required',`
       `'email' => 'email|unique:user,email,1,user_id'`
    `];`
In above example I have to pass value of the current item primary key instead of 1.

**Comment by joaosalless** [comment]
If you are sending the `user_id` field on the form, try this:

```php
return [
	'name'  => 'required',
	'email'  => 'unique:users,email,'.\Request::get('user_id').',user_id',
];
```

**Comment by golinmarq** [comment]
@joaosalless hey Joao how can be this done in the LaravelValidator when you are updating a value and have to set this as unique?

**Comment by golinmarq** [comment]
you should check this https://github.com/andersao/laravel-validator/issues/7

**Comment by mhetreramesh** [comment]
Thanks @joaosalless and @golinmarq, I will try both of these solutions. I did handled uniqueness check in the controller previously.
