### ISSUE TITLE
Is there a method for limit rows?

### ISSUE THREAD

**Issue by eullercristian** [andersao/l5-repository#251]
Dears, 

How i use limit rows in the model using l5? How is the best way?

Example: `$this->findWhere()->limit(10)`

Thanks a lot

**Comment by joaosalless** [comment]
Hello @eullercristian. I use the `take()` function:

```php
$this->findWhere()->take(10);
```

**Comment by Glorian** [comment]
@eullercristian, there is two options:

1.  Limit in sql query: 
```php
$objectRepository
    ->scopeQuery(function($query) {
        return $query->take(10);
    })
    ->all();
```
2. Limit result collection: @joaosalless already wrote

In most cases query limitation is more preferable.

**Comment by anhtuannguyentran** [comment]
It's not worked if use CacheableRepository.
