### ISSUE TITLE
Is there any way to change the condition Or to And?

### ISSUE THREAD

**Issue by wugang8068** [andersao/l5-repository#261]
The question makes my fuzzy, for example: the following url will make a query string:

`http://localhost:2222/profUsers?limit=20&page=1&search=enabled:0;real_name:%E6%B5%8B%E8%AF%95`

and the sql is:

`select * from`dingjia`.`inf_prof_user`where (`dingjia`.`inf_prof_user`.`real_name`like ? or`dingjia`.`inf_prof_user`.`enabled`= ?) limit 20 offset 0`

And the question is how to make the 'Or' to 'And' like this:

`select * from`dingjia`.`inf_prof_user`where (`dingjia`.`inf_prof_user`.`real_name`like ? and`dingjia`.`inf_prof_user`.`enabled`= ?) limit 20 offset 0`

**Comment by caophong** [comment]
this is aswer:
https://github.com/andersao/l5-repository/issues/219
