### ISSUE TITLE
deleteWhere method modifies the model to be instance of Query builder and not instance of Eloquent

### ISSUE THREAD

**Issue by vlatkorun** [andersao/l5-repository#263]
The applyConditions method called in deleteWhere does this.

The method should be like this:
`/**
     * Applies the given where conditions to the model.
     *
     * @param array $where
     * @return void
     */
    protected function applyConditions(array $where)
    {
        foreach ($where as $field => $value) {
            if (is_array($value)) {
                list($field, $condition, $val) = $value;
                $this->model->where($field, $condition, $val);
            } else {
                $this->model->where($field, '=', $value);
            }
        }
    }`

The model class will not be replaced then.

**Comment by FilipNikolovski** [comment]
There is already a fix in the PRs https://github.com/andersao/l5-repository/pull/249 just needs to get merged.

**Comment by eullercristian** [comment]
ping @ionut-tanasa  @andersao

**Comment by Numline1** [comment]
Ping @ionut-tanasa @andersao @eullercristian - This is still an issue :(

**Comment by eullercristian** [comment]
@Numline1 I not have access to write in this repository. :(

**Comment by Numline1** [comment]
@eullercristian sadly, I believe there were no changes in about 6 months, perhaps a fork of this nice package would be in order :]. I believe you're also a collaborator (ref #347), how's so you don't have a write access?

**Comment by eullercristian** [comment]
@Numline1 sorry, i received the invite today, i didnt see the e-mail. Fixed in https://github.com/andersao/l5-repository/releases/tag/2.6.7

**Comment by Numline1** [comment]
Wonderful, thank you
