### ISSUE TITLE
Route is not added in Laravel 5.3

### ISSUE THREAD

**Issue by golinmarq** [andersao/l5-repository#275]
Documentation says: 

> The command will also create your basic RESTfull controller so just add this line into your routes.php file and you will have a basic CRUD

I think this only works with Laravel <5.2. In Laravel 5.3 routes is not a file but a folder

**Comment by RienMoeyaert** [comment]
Not tested, but you could still add the `Route::resource('cats', CatsController::class);` in one of the files within the routes folder I'd guess, no?

**Comment by golinmarq** [comment]
Sure, you can do that I'll be working on this and make the PR when I have time

**Comment by eullercristian** [comment]
@golinmarq  The error persist?

**Comment by golinmarq** [comment]
@eullercristian yes, but I desist to work with this anymore
