### ISSUE TITLE
stubsOverridePath config not working

### ISSUE THREAD

**Issue by ptsilva** [andersao/l5-repository#283]
In the
`Prettus\Repository\Generators\Generator:81` the Generator use `config('repository.generator.stubsOverridePath', __DIR__);`,
but the default config file set to stubsOverridePath at 'repository.generator.paths.stubsOverridePath'. i think the config file or the implementation of `Prettus\Repository\Generators\Generator` is wrong

**Comment by zjien** [comment]
yes, I found it also ,hope to merge the PR

**Comment by ptsilva** [comment]
ping @eullercristian

**Comment by ptsilva** [comment]
can you merge this ?
