### ISSUE TITLE
How to restrict applying query parameters to specific Repositories only?

### ISSUE THREAD

**Issue by Mahmoudz** [andersao/l5-repository#290]
Say I have an endpoint with `search` query parameter and I am querying 2 repositories, how to apply that `search` on the second repository only?

**Here's my case:**
- I have an endpoint that lists Rewards: `http://api.my-app.dev/rewards?search=name:apple%20gift%20card` 
- The endpoint can have `search` query parameter to find Rewards by names.
- On that endpoint I am applying a Middleware, that tries to find a User by its visitor ID.
- Here's how the Middleware tries to find the user `$this->userRepository->findByField('visitor_id', $visitorId)->first();`
- After the user is found I authorize it to proceed and query the Rewards `$this->rewardRepository->paginate();`

The problem is I only need to apply that `search` query when getting the rewards, but it gets applied to finding the user as well. How to prevent it from being applied everywhere and only restrict it to specific Repositories?

**Comment by andersao** [comment]
try this :
`$this->userRepository->skipCriteria()->findByField('visitor_id', $visitorId)->first();`

**Comment by Mahmoudz** [comment]
@andersao seems like `skipCriteria` will solve it. Thanks
