### ISSUE TITLE
Pagination offset?

### ISSUE THREAD

**Issue by danields** [andersao/l5-repository#299]
So I can limit the number of results I can get with pagination, like this:

`$companies = $this->companyRepository->paginate(50, ['id', 'name']);`

That will return the first 50 items from the repository. If the repository has 150 items, this would be page 1. So let's say I want page 2 (items 51 through 100), how do I get it? How do I specify the pagination offset? The paginate() method doesn't seem to accept a pagination offset parameter.

**Comment by joaosalless** [comment]
```php
$currentPage = 5;
$totalPerPage = 10;

// force current page to 5
Paginator::currentPageResolver(function() use ($currentPage) {
    return $currentPage;
});

// list all users, with 10 users per page, on page 5
$users = User::all()->paginate($totalPerPage);
```

**Comment by samirnijenhuis** [comment]
A little bit late to the party, I assume you already solved it on your own. You can do two things I think:

1. If you use the ?page= parameter the paginator will automatically pick it up and set the offset for you. 
2. Let your repositories extend your own 'baserepository' which extends the package's BaseRepository ( similar to the Controller.php in laravel ). Example: 
`<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;

abstract class Repository extends BaseRepository {

    /**
     * Retrieve all data of repository, paginated
     *
     * @param null $limit
     * @param int $page
     * @param array $columns
     * @param string $method
     * @return mixed
     */
    public function paginate($limit = null, $page = null, $columns = ['*'], $method = "paginate")
    {
        $this->applyCriteria();
        $this->applyScope();
        $limit = is_null($limit) ? config('repository.pagination.limit', 15) : $limit;
        $results = $this->model->{$method}($limit, $columns, 'page', $page);
        $results->appends(app('request')->query());
        $this->resetModel();

        return $this->parserResult($results);
    }
}`

I hope this helps.

**Comment by kobusbeets** [comment]
**Laravel Version 5.8**

I use a similar approach to @joaosalless but I have instead placed it in middleware that runs globally. You can optionally add it to individual routes.

```shell
php artisan make:middleware ConfigurePagination
```

Update the middleware class: app/Http/Middleware/ConfigurePagination.php

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Pagination\Paginator;

class ConfigurePagination
{
    public function handle($request, Closure $next)
    {
        Paginator::currentPageResolver(function() use($request) {
            return $request->query('offset') ?? $request->query('page') ?? 0;
        });
        return $next($request);
    }
}
```

Add it to the global middleware array in app/Http/Kernel.php

```php
protected $middleware = [
        ...,
        App\Http\Middleware\ConfigurePagination::class
];
```
