### ISSUE TITLE
With Multiple relations 

### ISSUE THREAD

**Issue by vijaythecoder** [andersao/l5-repository#322]
I tried to find docs, source code  and issues but no luck. Is there an option to get the results with multiple relations?
http://api.example.dev/api/orders?with=employee,customer ? it works great with single relation. 
if this is not available yet? can you please let me know the place of the source file? I will try to tweak and contribute

**Comment by petarjs** [comment]
Hi, try using `;` instead of `,` :)

For example
```
/v1/entries?with=photos;author;tags
```
