### ISSUE TITLE
use transaction?

### ISSUE THREAD

**Issue by caophong** [andersao/l5-repository#323]
is that the best way to use transaction?

        try {
            DB::connection()->beginTransaction();
            $this->myRepository->delete($id);
            $this->myRepository->insert($data); 
            DB::connection()->commit();
        } catch (\PDOException $e) {
            DB::connection()->rollback();
            throw new \Exception($e->getMessage());
        }

**Comment by Hytii** [comment]
I personally do it that way too in a service layer which deal with logic and transactions like in your example

**Comment by joaopaulopvillela** [comment]
Good Morning

I am trying to execute a transaction, but I am not consequently, I already placed inside a block of treatment, but every time it gives an error it persists the data of the transaction, there is some configuration that has to be performed.

Thanks
