### ISSUE TITLE
Generator broken for Laravel 5.4

### ISSUE THREAD

**Issue by hayeah** [andersao/l5-repository#332]
Generator throws error.

> php artisan make:entity Blah

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found
```

Fixed in #331

**Comment by altaraven** [comment]
+1 Please add Laravel 5.4.* support.

**Comment by VRuzhentsov** [comment]
Anyone know? Is this project alive? or, it is time to start search new laravel repository project ?

**Comment by JunJun-Love-Amber** [comment]
+1, 60 issues were opened .Where is the author?

**Comment by marciodiasdev** [comment]
+1

**Comment by yljphp** [comment]
+1

**Comment by eullercristian** [comment]
@ionut-tanasa  @andersao  please, solve the issue, for we can use the package in Laravel 5.4. Thanks a lot!

**Comment by victorffarias** [comment]
Apparently the trait AppNamespaceDetectorTrait had a modification changing its name to DetectsApplicationNamespace so to make the generator to work in versions 5.4+ of Laravel simply has to use the DetectsApplicationNamespace class

**Comment by igorbrum** [comment]
@victorffarias thanks a lot! It's work :)

**Comment by joaosalless** [comment]
The PR #330 makes the package compatible with versions 5.1, 5.2, 5.3 and 5.4.

`Illuminate\Console\AppNamespaceDetectorTrait` is not required.

```php
/**
 * Get application namespace
 * 
 * @return string
 */
public function getAppNamespace()
{
    return \Illuminate\Container\Container::getInstance()->getNamespace();
}


/**
 * Get class name.
 *
 */
public function getRootNamespace()
{
    return config('repository.generator.rootNamespace', $this->getAppNamespace());
}
```

**Comment by cmzz** [comment]
@igorbrum  How does it work.

**Comment by JunJun-Love-Amber** [comment]
u can go to [Pull requests](https://github.com/andersao/l5-repository/pull/330) and read the  Files changed

**Comment by igorsbrum** [comment]
@cmzz Hi, sorry for the late response.

in \Prettus\Repository\Generators\Generator.php i replace AppNamespaceDetectorTrait to DetectsApplicationNamespace

Not the best practice but... You can look http://igniz87.hatenablog.com/entry/2017/01/25/122435

**Comment by igorbrum** [comment]
@cmzz Hi, sorry for the late response.

in \Prettus\Repository\Generators\Generator.php i replace AppNamespaceDetectorTrait to DetectsApplicationNamespace

Not the best practice but... You can look http://igniz87.hatenablog.com/entry/2017/01/25/122435

**Comment by cmzz** [comment]
@igorbrum Thanks. I've got it.

I think you can pull requests to fix that bug. 👍

**Comment by erayaydin** [comment]
:+1: please fix

**Comment by KamalHr** [comment]
Quickly fixed by changing ligne 5 in vendor/laracasts/generators/src/Commands/MigrationMakeCommands.php
into : `use Illuminate\Console\DetectsApplicationNamespace;` and ligne 16 into : `use DetectsApplicationNamespace;`

**Comment by erayaydin** [comment]
This should be merged on repository. Directly change on `vendor` is not a good way

**Comment by eullercristian** [comment]
Please Andersão, fix the problem, there are many PRs about this question !
Thanks a lot!


  <https://mailtrack.io/> Enviado com Mailtrack
<https://mailtrack.io/install?source=signature&lang=pt&referral=eullercdr@gmail.com&idSignature=24>

2017-02-19 14:12 GMT-03:00 Eray AYDIN <notifications@github.com>:

**Comment by erayaydin** [comment]
This problem fixed on `master` branch but not tagged. It should be tagged as new version. Its already fixed. You can select `dev-master` version for this package.

**Comment by topone4tvs** [comment]
You Can add this code
$this->app->alias('Illuminate\Console\AppNamespaceDetectorTrait', 'Illuminate\Console\DetectsApplicationNamespace');

It can solve this issue for a short time

**Comment by eullercristian** [comment]
Laravel 5.4 its working :)
