### ISSUE TITLE
findWhere with OR

### ISSUE THREAD

**Issue by quinhone** [andersao/l5-repository#335]
How can I make a query using the OR at findWhere?

**Comment by thekaduu** [comment]
By default the query uses the OR.

**Comment by desertfoxmb** [comment]
Unless I'm missing something this would appear to be incorrect. Using multiple conditions on a findWhere always results in an and.

For example $this->repository->findWhere(['col1'=>1, 'col2=>2]) results in a query select * from table where col1=1 and col2=2;
