### ISSUE TITLE
Illegal offset type

### ISSUE THREAD

**Issue by Webysther** [andersao/l5-repository#339]
I receive this error after create new resource:

```
2
"Illegal offset type"
"/var/www/vendor/hoa/core/Event.php"
202
array:1 [▼
  "eventId" => RepositoryEntityCreated {#500}
]
```

![error](https://cloud.githubusercontent.com/assets/750007/22921495/2029b7c0-f281-11e6-9718-287b75af5a74.png)

Any ideias? :)

**Comment by Webysther** [comment]
I discovery, `Hoa\Core` override this function: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L468

**Comment by uyab** [comment]
Hi @Webysther, today I got the same problem, how do you overcome this issue?

**Comment by Webysther** [comment]
I remove/update the package using `Hoa/Core`. Using compose show is possible to check how package is using, this package use another dependency.

**Comment by Webysther** [comment]
Mostly packages move forward from this lib, update maybe fix.
