### ISSUE TITLE
How should I get the route parameters in criteria?

### ISSUE THREAD

**Issue by cmzz** [andersao/l5-repository#341]
Cant work with Input::get().

`Route::get('users/{userId}/cards', 'UsersController@index');`

My Criteria Code:

		class WithUserCriteria implements CriteriaInterface
		{
		    /**
		     * Apply criteria in query repository
		     *
		     * @param                     $model
		     * @param RepositoryInterface $repository
		     *
		     * @return mixed
		     */
		    public function apply($model, RepositoryInterface $repository)
		    {
		        $userId = Input::get('userId');
		        $userId = request('userId');
		        $userId = $_REQUEST['userId'];
		        $model = $model->where('user_id', Input::get('userId'));
		        return $model;
		    }
		}

And in my Controller:

		$this->userCardRepository
		    ->pushCriteria(WithUserCriteria::class)
		    ->pushCriteria(UserValidCardCriteria::class)
		    ->all();

The userId is null.

**Comment by Webysther** [comment]
Add in criteria:

```php
   /**
     * @var \Illuminate\Http\Request
     */
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }
```

after get the ID from resource URL, to know how get resource list of user:

```shell
$ php artisan route:list --name=user
```

And add the key indentity to request inside criteria:

```php
public function apply($model, ... $repository)
    {
        $uid = $this->request->route('user');
```

**Comment by cmzz** [comment]
@Webysther Thanks.
