### ISSUE TITLE
BaseRepository::sync

### ISSUE THREAD

**Issue by schursin** [andersao/l5-repository#352]
Bug? No $id attribute

```
    /**
     * Sync relations
     *
     * @param $id
     * @param $relation
     * @param array $attributes
     * @return $this
     */
    public function sync($relation, $attributes)
```

**Comment by eullercristian** [comment]
I will check this question now

**Comment by eullercristian** [comment]
@schursin  Did you tested this method? How error you get?

**Comment by schursin** [comment]
@eullercristian It work good on BelongsTo relations, but on BelongsToMany we need an "id"...

**Comment by schursin** [comment]
... or comment fix :)

**Comment by schursin** [comment]
IMHO, we need a comment fix, that's all :)

**Comment by eullercristian** [comment]
Fixed in tag 2.6.10 :)

**Comment by schursin** [comment]
@eullercristian tnx!

**Comment by Quiss** [comment]
```
-   public function sync($relation, $attributes)
+   public function sync($id, $relation, $attributes)
      {
          $this->model = $this->model->with($relation)->getRelation($relation)->sync($attributes);
          return $this;
```

Nice, added attribute, and no use. Good work @eullercristian 😄

**Comment by eullercristian** [comment]
@Quiss  and @schursin  really, i have a mistake, sorry, i fix in 2.6.11, i will review the method for use with BelongsToMany

**Comment by schursin** [comment]
It seems to be

```
    /**
     * Sync relations
     *
     * @param $id
     * @param $relation
     * @param array $attributes
     * @return $this
     */
    public function sync($id, $relation, $attributes)
    {
        return $this->find($id)->getRelation($relation)->sync($attributes);
    }
```

**Comment by eullercristian** [comment]
@schursin  Can you send a PR?

**Comment by Quiss** [comment]
@schursin 👍

**Comment by schursin** [comment]
@eullercristian ok

**Comment by Quiss** [comment]
@eullercristian one question, you're testing this code ?

**Comment by eullercristian** [comment]
@Quiss  Yes, i do, i use this package in all my projects, in this case , i have a mistake i didnt try for use with BelongsToMany

**Comment by schursin** [comment]
@eullercristian https://github.com/andersao/l5-repository/pull/353

**Comment by eullercristian** [comment]
@schursin and @Quiss  done in 2.6.13
