### ISSUE TITLE
prettus/laravel-validator - Compatibility with lumen 5.4

### ISSUE THREAD

**Issue by ace05** [andersao/l5-repository#365]
Hi,

I got a following error when use prettus/laravel-validator at lumen 5.4

`BindingResolutionException in Container.php line 804:
Target [Illuminate\Contracts\Translation\Translator] is not instantiable while building [PCKM\Validators\UserValidator, Illuminate\Validation\Factory].`

Can you suggest me how to resolve it.

**Comment by meNESS** [comment]
I have the same problem.

**Comment by meNESS** [comment]
I don't think it's related to Lumen compatibility, it cannot instantiate the interface `Translator` and its because of the making validation. A workaround is to modify the `__construct()` method of `BaseRepository` and comment the `$this->makeValidator()` line.

```php
public function __construct(Application $app)
    {
        $this->app = $app;
        $this->criteria = new Collection();
        $this->makeModel();
        $this->makePresenter();
        //$this->makeValidator();
        $this->boot();
    }
```

**Comment by Patskimoto** [comment]
Has anyone found a way to get this to work? I want to use the validator in Lumen so commenting the `$this->makeValidator()` out isn't really an option and I believe doing so stops any validation from occuring.

**Comment by rodralme** [comment]
Register 'Illuminate\Contracts\Translation\Translator' class in yours AppServiceProvider:

public function register()
    {
        App::bind(Translator::class, function ($app) {
            return $app['translator'];
        });
}

refs: https://github.com/andersao/l5-repository/issues/28

I hope that it works!
