### ISSUE TITLE
Provider already exists!

### ISSUE THREAD

**Issue by sandeepv** [andersao/l5-repository#385]
I am getting this error when i run  "php artisan make:entity User"
[Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path C:\xampp\htdocs\moderation\src\Moderation\Repository/Providers/RepositoryServiceProvide
  r.php

Here is my config:
'generator'  => [
        'basePath'      => base_path('src'.DIRECTORY_SEPARATOR.'Moderation'.DIRECTORY_SEPARATOR.'Repository') . '',
        'rootNamespace' => 'Moderation\\Repository\\',
        'paths'         => [
            'models'       => 'Entities',
            'repositories' => 'Repositories',
            'interfaces'   => 'Repositories',
            'transformers' => 'Transformers',
            'presenters'   => 'Presenters',
            'validators'   => 'Validators',
            'controllers'  => 'Http/Controllers',
            'criteria'     => 'Criteria',
            'stubsOverridePath' => app_path()
        ]
    ]

**Comment by curder** [comment]
Publish Configuration
```
php artisan vendor:publish --provider "Prettus\Repository\Providers\RepositoryServiceProvider"
```

**Comment by sandeepv** [comment]
It have run the command php artisan vendor:publish --provider "Prettus\Repository\Providers\RepositoryServiceProvider

it says "Publishing complete."
but still the same issue

**Comment by curder** [comment]
```
☁  study_repository [master] ⚡ ll app/Providers
total 48
-rw-r--r--  1 luo  admin   456B  5 15 09:44 AppServiceProvider.php
-rw-r--r--  1 luo  admin   575B  5 12 14:50 AuthServiceProvider.php
-rw-r--r--  1 luo  admin   380B  5 12 14:50 BroadcastServiceProvider.php
-rw-r--r--  1 luo  admin   596B  5 12 14:50 EventServiceProvider.php
-rw-r--r--  1 luo  admin   597B  5 15 09:57 RepositoryServiceProvider.php
-rw-r--r--  1 luo  admin   1.5K  5 12 14:50 RouteServiceProvider.php
☁  study_repository [master] ⚡ rm -f app/Providers/RepositoryServiceProvider.php
☁  study_repository [master] ⚡ php artisan vendor:publish --provider "Prettus\Repository\Providers\RepositoryServiceProvider"


  [ErrorException]
  include(/Volumes/codes/Study/laravel/study_repository/vendor/composer/../../app/Providers/RepositorySer
  viceProvider.php): failed to open stream: No such file or directory


☁  study_repository [master] ⚡ composer dump-autoload
Generating optimized autoload files
☁  study_repository [master] ⚡ php artisan vendor:publish --provider "Prettus\Repository\Providers\RepositoryServiceProvider"


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'App\Providers\RepositoryServiceProvider' not found

☁  study_repository [master] ⚡ vim app/Providers/AppServiceProvider.php
☁  study_repository [master] ⚡ php artisan vendor:publish --provider "Prettus\Repository\Providers\RepositoryServiceProvider"
Publishing complete.
```

Because i register the repository service provider in `app/Providers/AppServiceProvider.php`, when i modify this file,like this
```
/**
 * Register any application services.
 *
 * @return void
 */
public function register()
{
//       $this->app->register(RepositoryServiceProvider::class);
}
```
if your are register it in your `config/app.php` add `App\Providers\RepositoryServiceProvider::class` to the end of the providers array:
```
'providers' => [
    ...
    App\Providers\RepositoryServiceProvider::class,
],
```
your also should annotate it.

* * * * *

The `RepositoryServiceProvider.php` file like this:

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(
            'App\Repositories\YourRepository',
            'App\Repositories\YourRepositoryEloquent'
        );

        ......
    }
}
```

**Comment by brunocascio** [comment]
@sandeepv 

I'm facing the same issue. Any luck?
