### ISSUE TITLE
fieldSearchable works only with get?

### ISSUE THREAD

**Issue by lucassmacedo** [andersao/l5-repository#393]
Hello! I want use fieldSearchable whit post request.. its possible? i try, but did not have success.

**Comment by johannesschobel** [comment]
this may not work. The semantics of `POST` is to add data to the server (e.g., create something new). `GET` however, requests data from the server, so filtering is a common use-case.

Regarding the `POST` semantics: What should the `fieldSearchable` do in your opinion?! At least for me, this makes no sense..

Cheers
