### ISSUE TITLE
How to create a new query param? 

### ISSUE THREAD

**Issue by devingray** [andersao/l5-repository#401]
Looking at the docs there is 
`http://prettus.local/users?filter=id;name` 

I want to add a new one for pagination

`http://prettus.local/users?filter=id;name&paginate=10`

Where 10 would be the limit for the pagination

Is there built in functionality for this or how would I go about building this?

**Comment by johannesschobel** [comment]
simply use `?limit=100` in order to specify how many items should be displayed on one page, and `?page=3` in order to show the items on page 3. Of course you can combine both params!
