### ISSUE TITLE
Bring users related to a specific item.

### ISSUE THREAD

**Issue by tsdeveloper** [andersao/l5-repository#406]
Good evening, I would like to bring users have rules equal to "Delivery" how do I?
Being Users is related to many rules table for many.
I've tried it that way, but it's bringing me all the users.
`  $deliverymans =$user->with('Roles', function($query) {
    return $query->where('name', 'Delivery');
    })->lists();`

**Comment by johannesschobel** [comment]
Try this:
```php
$users = $repository->whereHas('roles', function($q) use ($roles) {
   return $q->where('name', '=', 'Delivery');
})->paginate();
```

where `$repository` is your `UserRepository` and `roles` is the name of the relationship between `User` and `Role`

**Comment by tsdeveloper** [comment]
Solve it this way

   $ Deliverymans = User :: with (['roles' => function ($ q) {
             $ Q-> where ('role_id', 2);
         }]) -> whereHas ('roles', function ($ query) {
             $ Query-> where ('role_id', 2);
         }) -> lists ('name', 'id');

When I did so I used his example with the whereHas in the l5-repository he gave an error stating that there is no whereHas. I think that's why I'm using L5 Repository in version 2.1.5

**Comment by tsdeveloper** [comment]
Sorted out...
