### ISSUE TITLE
How to use a different repository in controller?

### ISSUE THREAD

**Issue by artlivemediarepos** [andersao/l5-repository#407]
I would like to use two different repositories in one controller. for example in TeamController I have this construct method,

` public function __construct(TeamRepository $repository)
{
        $this->repository = $repository;
}`

I would like to use UserRepository as well in the same controller. I know we can use it like this `__construct(TeamRepository $repository, UserRepository $userRepository)` but what if I wanted to use more repositories. Is there any other to achieve this? Thanks!

**Comment by devingray** [comment]
You can new up a class
```
$repository = app('App\Interfaces\ReleaseRepository');
$repository->setPresenter(ReleasePresenter::class);
$releases = $repository->scopeQuery(function($query){
    return $query->withTrashed();
})->find($release_ids);
```

**Comment by mrajabtech** [comment]
Thanks! That was simple!
