### ISSUE TITLE
Command "make:entity" is not defined.

### ISSUE THREAD

**Issue by Snarcraft** [andersao/l5-repository#413]
Command  doesn't work

**Comment by joaosalless** [comment]
Make sure you have included the `Prettus\Repository\Providers\RepositoryServiceProvider::class,` in `config/app.php` settings.

If this is not the cause of the problem, review the [installation documentation](https://github.com/andersao/l5-repository#installation) or inform the version of the l5-repository package and the version of the Laravel framework.
