### ISSUE TITLE
SQL injection attacks: does it exist?

### ISSUE THREAD

**Issue by talliujobs** [andersao/l5-repository#414]
` http://prettus.local/users?search=John&searchFields=name:like `
` http://prettus.local/users?filter=id;name&orderBy=id&sortedBy=desc ` 
` http://prettus.local/users?search=name:John Doe;email:john@gmail.com `

do these routes exist the risk of SQL injection attacks? 
if I don't hide a column in the ORM, someone may access the route ` http://prettus.local/users?search=is_admin:1 `, how can I prevent this?   Is there a list to protect the column ?

**Comment by johannesschobel** [comment]
in a repository, you can define the columns that are searchable..
Please read the readme and search for `fieldsSearchable`!

**Comment by ptsilva** [comment]
The Criteria request apply any sql fragment with query builder. This probably is safe. 
The issue that exists here, is in ```include```, cause error if relationship not exists. But is not a security problem.

**Comment by talliujobs** [comment]
thanks, I understand now.
