### ISSUE TITLE
Bug on Stub over-riding

### ISSUE THREAD

**Issue by edsamonte** [andersao/l5-repository#417]
On https://github.com/andersao/l5-repository/blob/master/src/Prettus/Repository/Generators/Generator.php
```
public function getStub()
    {
        $path = config('repository.generator.stubsOverridePath', __DIR__);
        if(!file_exists($path . '/Stubs/' . $this->stub . '.stub')){
            $path = __DIR__;
        }
        return (new Stub($path . '/Stubs/' . $this->stub . '.stub', $this->getReplacements()))->render();
    }
```

Notice that `'repository.generator.stubsOverridePath'` is being used, whereas on
https://github.com/andersao/l5-repository/blob/master/src/resources/config/repository.php
```
'generator'  => [
        'basePath'      => app_path(),
        'rootNamespace' => 'App\\',
        'paths'         => [
            ...
            'stubsOverridePath' => app_path()
        ]
    ]
```

... `'repository.generator.paths.stubsOverridePath'` is the one defined.

**Comment by ptsilva** [comment]
#284 
#283 
I already opened this issue. This must be merged.

**Comment by edmandiesamonte** [comment]
Wow. Your fix was already months ago. Got me questioning if this repo is still maintained.
