### ISSUE TITLE
Fix for Laravel 5.5: hidden attributes of model are required when calling create and updates.

### ISSUE THREAD

**Issue by sroutier** [andersao/l5-repository#424]
Already identified and fixed on PR #255.
Please merge. Just used it with the latest Laravel works perfectly.

Thanks.
/S

**Comment by sroutier** [comment]
ok, so I see now that a similar PR was merged by @michalisantoniou6 on Mar 24, but then on Apr 7 @eullercdr reverted the change. I can't figure out why. Would anybody know?
This looks to me like it is required for Laravel 5.4+,  is it incompatible with previous versions?

Thanks.
/S

**Comment by dzung1nguyen** [comment]
Same issue, i think laravel 5.5 just released, so they updated something in core,
It work good from laravel 5.4 from a few day before, but when i created a project by laravel 5.4 on today, i get an error like you :(

$this->user->create($input); -> error: missing password
User::create($input); -> work good

**Comment by andersao** [comment]
I will see this bug guys!

**Comment by AEChabok** [comment]
Same issue, in laravel 5.4 
how fix it?

**Comment by AEChabok** [comment]
if (!is_null($this->validator)) {
    $attributes = $this->model->newInstance()->forceFill($attributes)->toArray();    <=== In this step, the hidden fields are not set
    $this->validator->with($attributes)->passesOrFail(Validator::RULE_CREATE);
}

**Comment by AEChabok** [comment]
remove this line 
"$attributes = $this->model->newInstance()->forceFill($attributes)->toArray();"
from create and update function in base repository then fix it

**Comment by andre-bahia** [comment]
Same issue, in lumen 5.5

**Comment by andersao** [comment]
Hi guys! The problem was fixed and I will release a new version soon.
