### ISSUE TITLE
how to generate singular controller

### ISSUE THREAD

**Issue by springjk** [andersao/l5-repository#430]
`php artisan make:entity User` will generate `UsersController`, I do not know why this is a plural design，but i want a singular controller  such as `UserController`, I did not find a configuration item about it. What did I miss?

**Comment by leonardollobato** [comment]
+1

**Comment by Maras0830** [comment]
```
$ php artisan make:resource Home
```

**Comment by matinwd** [comment]
I dunno how this solution related to topic

> ```
> $ php artisan make:resource Home
> ```

**Comment by matinwd** [comment]
Okay. I don't know if this is the best answer, but if you are wondering how you can change this settings, you can change 
```
public function getControllerName()
    {

        return ucfirst($this->getPluralName());
    }
```
to:
```
public function getControllerName()
    {

        return ucfirst($this->getSingularName());
    }
```
I'm not sure this is a clean way to do.
