### ISSUE TITLE
Laravel 5.5 - Artisan command with fire method

### ISSUE THREAD

**Issue by romarioliveira25** [andersao/l5-repository#433]
Hey all,

So, I had checked from the latest update of Laravel the fire method used in Artisan Commands has been renamed to handle and this had causing errors when try use the make commands added by l5-repository (make:entity, make:repository, etc).

As workarround, I had follow the recommendation indicated at [this post](https://laracasts.com/discuss/channels/laravel/tinkercommandhandle-does-not-exist) in laracasts.

Well, I little detail to change, but hope this helps :)

**Comment by romarioliveira25** [comment]
Whoops, 

Has been mentioned at [this pull request](https://github.com/andersao/l5-repository/pull/410/files).

**Comment by andersao** [comment]
I released a new version with the fix.
