### ISSUE TITLE
$this->repository->find($id) returning random result that doesn't match $id

### ISSUE THREAD

**Issue by paperscissors** [andersao/l5-repository#438]
Hi folks, I'm using the latest version of prettus/l5-repository on Laravel 5.3.31.

I'm finding for some reason when I do a `$this->repository->find($id)->first()` on my controller for any entity, the repository returns a single random result that has nothing to do with the $id I'm passing.

I'm not seeing a pattern, i.e. for my Product entity if I pass id 67198 it shows me a result for one with 61028; if I pass id 50 for Artist entity I get the data corresponding with id 1.

Otherwise edit, update, index, etc are all returning what I'd expect.

I haven't done any modifications to the underlying repositories or interfaces. Just noticed this because I'm trying to test out some API functionality and realized it's passing back the wrong models. I was pretty sure this was working when I first set this all up, so kind of at a loss as to why I'm getting the wrong results, now.

Any ideas?

**Comment by berzley** [comment]
I should only need to run `$this->repository->find($id);` to return the model. If you're using a presenter it should return it presented as you have setup.
