### ISSUE TITLE
how can I cancel print 'data' key in json when I presenter transformer

### ISSUE THREAD

**Issue by learnmove** [andersao/l5-repository#439]
**output is**
{
"output_json": {
"data": {
"_id": 1,
"text": "Exercitationem rem pariatur aut hic.",
"created_at": {
"date": "2017-09-19 07:26:47.000000",
"timezone_type": 3,
"timezone": "UTC"
},
"updated_at": {
"date": "2017-09-19 07:26:47.000000",
"timezone_type": 3,
"timezone": "UTC"
},
"user": {
"data": {
"_id": 1,
"name": "弓馨",
"created_at": {
"date": "2017-09-19 07:26:47.000000",
"timezone_type": 3,
"timezone": "UTC"
},
"updated_at": {
"date": "2017-09-19 07:26:47.000000",
"timezone_type": 3,
"timezone": "UTC"
}
}
}
}
}

**I just want**
{
"output_json": {
"_id": 1,
"text": "Exercitationem rem pariatur aut hic.",

"user": {
"_id": 1,
"name": "弓馨",

how can I cancel data key

**Comment by cosmok** [comment]
In the config have tried setting the 'serializer' key to League\Fractal\Serializer\ArraySerializer::class ?
