### ISSUE TITLE
Is there any plan to have this repo maintained in the future? 

### ISSUE THREAD

**Issue by devingray** [andersao/l5-repository#445]
Hey, This is most probably my favorite package for Laravel and may just as well be the best thing on the internet. 

I do however want to know if there is any plan for ongoing development for this package? Life happens and we get busy, but I think as a community we can keep this going with minor fixes and improvements?

Just a question, would love to hear from anybody that would be keen to do this together. #

**Comment by Maras0830** [comment]
agree, and I really want this pr can be merged...

https://github.com/andersao/l5-repository/pull/442

or 5.5 make:controller issue can't use ..

maybe i can help chinese issue

**Comment by tawenxi** [comment]
对你这个pr 很满意

**Comment by devingray** [comment]
There are 27 open pull requests currently. opening more will not equal a maintained repository

**Comment by eullercdr** [comment]
@Maras0830 You PR was merge, check that!

**Comment by eullercdr** [comment]
@devingray Do you have time to collaborate with the repository? All members here was very busy. If you want, send me a e-mail eullercdr@gmail.com
