### ISSUE TITLE
[BUG][2.6.22] CacheableRepository needs to call resetModel() after retrieving value

### ISSUE THREAD

**Issue by dmason30** [andersao/l5-repository#446]
There is a significant bug when using the CacheableRepository where by if a result is returned from database then `resetModel` is called, however, if a result is returned from the `Cache` then `resetModel` is not called, please see example below. 

**Prettus\Repository\Eloquent\BaseRepository@all**
In `Prettus\Repository\Eloquent\BaseRepository` the `all` method calls `$this->resetModel()` before it returns the results:

    public function all($columns = ['*'])
    {
        ...
        $this->resetModel();
        $this->resetScope();

        return $this->parserResult($results);
    }

**Prettus\Repository\Traits\CacheableRepository@all**
In `Prettus\Repository\Eloquent\CacheableRepository` the `all` method DOEST NOT call `$this->resetModel()` before it returns the results:

    public function all($columns = ['*'])
    {
        ....
        $value = $this->getCacheRepository()->remember($key, $minutes, function () use ($columns) {
            return parent::all($columns);
        });
        
        //BUG: Should call $this->resetModel() here
        return $value;
    }

**Take this basic example:**

    $joe_results = $this->repo->where('first_name', 'Joe')->all();
    $customer_results = $this->repo->where('type', 'Customer')->all();

The `$joe_results` query is:

    SELECT * FROM table
    WHERE first_name = 'Joe'

Now if the `$joe_results` query is _CACHED_ then the model for the `$customer_results` query has NOT BEEN RESET!. 

So the `$customer_results` query ends up being:

    SELECT * FROM table
    WHERE first_name = 'Joe'
    AND type= 'Customer'

And thus would not return the correct result.

**Comment by eullercdr** [comment]
@dmason30  I will try this case and give to you a feedback. Thanks.
