### ISSUE TITLE
Update function not work

### ISSUE THREAD

**Issue by qiutuleng** [andersao/l5-repository#453]
hi.
I have an error in update function;
`Call to undefined method Illuminate\Database\Query\Builder::newInstance()`

my controller's code like:
```
public function update() {
    $this->repository->scopeQuery(function ($query) {
        /* @var Builder $query */
        return $query->withoutGlobalScope('published');
    });
    $this->repository->update($data, $id);
}
```

adding this scope is because I added a global scope to the model, so what should I do?
sorry, my English is not good.

**Comment by tawenxi** [comment]
这样肯定是不行的，withoutGlobalScope在model 实例里，不能用在Builder上

**Comment by qiutuleng** [comment]
@tawenxi 是newInstance方法在model上，l5-repository的update方法里面验证数据会用到$this->model->newInstance()方法获取一个新的实例。因为不移除全局作用域就查不出数据，移除全局作用域又要把model替换成builder对象。
感觉只能重写l5-repository的update方法了，但不想这样玩啊
