### ISSUE TITLE
Question regarding relations and criterias

### ISSUE THREAD

**Issue by henninghorn** [andersao/l5-repository#46]
I really enjoy using this package in my Lumen app.

I also really like the concept of criterias and how you can push them when you need them.
But I'm not sure to go around using them when it comes to relations.

I have a few tables, let's say articles and images.
All articles and images are tagged. So I also have a tags table, article_tag and image_tag table.

My current way to get articles tagged X is to use define a method on the Tag class:
````php
public function latest_news()
    {
        return $this->belongsToMany('App\Article')
            ->select([
                'articles.id',
                'articles.start_date',
                'articles.article_type',
                'articles.header',
                'articles.manchet',
                'articles.image_id'
            ])
            ->where('articles.status', 'published')
            ->where('articles.article_type', 'news')
            ->where('lang_id', config('lang_id'))
            ->orderBy('start_date', 'desc')
            ->limit(3);
    }
````

And then do this:
````php
$tags->with(['latest_news'])->find(1234)
````

What do you recommend, @andersao ?

**Comment by andersao** [comment]
Hello,

Today I also use something similar . At times I use presenters to bring some relationship information .

I added a new feature in RequestCriteria .

You can upload your relationships dynamically through the parameter *with*

http://api.local/tag?with=latest_news

It replaces the use of `$tags->with(['latest_news'])->find(1234)` in your controller .

You can change the parameter name to any other in the configuration file

**Comment by maxberg1c** [comment]
Hi,
is it possible to combine relationships and custom queries?
For example:
<code>job?with=skills&search=PHP&searchFields=skills:like</code>

In my Controller I have this:
<code>$this->jobRepository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $jobs = $this->jobRepository->with([
            'skills',
            'tasks',
            'company'
        ])->all();</code>

**Comment by biblicalph** [comment]
Hi, 

I have a similar question as maxberg1c. Suppose I have the relations listed below. 

class Country extends Model implements Transformable {
       protected $fillable = ['name', 'call_code', 'citizen'];
}

class State extends Model implements Transformable {
       protected $fillable = ['name', 'country_id'];

      public function country() {
            return $this->belongsTo('App\Country', 'country_id');
      }
}

class Office extends Model implements Transformable {
       protected $fillable = ['state_id', 'longitude', 'latitude', 'name', 'address'];
       
       public function state() {
           return $this->bleongsTo('App\Office', 'state_id');
       }
}

I retrieve the list of offices with the state and country relations in my controller using a repository like so.
$this->repo->with('state')->with('state.country')->all();

How can I add a search criteria that limits the results to offices in a specific country? 

Many thanks for your help

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by ionut-tanasa** [comment]
@maxberg1c and @biblicalph currently RequestCriteria does not support relation filtering.

I have something planned but it will take some time to implement it. It's kinda tricky.

Will do in future releases.
