### ISSUE TITLE
Question. Transform an array using a presenter and transfromer

### ISSUE THREAD

**Issue by devingray** [andersao/l5-repository#467]
This may be a broad question here, but any help will be really appreciated. I am using elastic search to retrieve data for an API. 

I then want to transform the data that comes from elastic search. The problem is that it does not return an eloquent model. 

So... in my controller I do this

```
$history = (new ElasticSearch())->searchForExactMatch(['user_id' => $id])->getPageData();
$presenter = new HistoryPresenter();
return $this->respondWithSuccess($presenter->present($history));
```

and I have a transformer that looks like this 

```
/**
     * Transform the \Histor entity
     * @param History $array
     *
     * @return array
     */
    public function transform($array)
    {
        return [
            'id'         => null,
            'type' => 'History',
            'history' => $array
        ];
    }
```

I understand that the transformer is coupled to a repository entity, but wonder if there is a technique that I may use to transform this data similarly to the way a model is transformed

**Comment by andrewmclagan** [comment]
You could hydrate the Eloquent models from ES results:

https://github.com/ethical-jobs/ethical-jobs-elasticsearch/blob/v1.5.2/src/Hydrators/EloquentHydrator.php

thats how we do it
