### ISSUE TITLE
I want in Repository use Validator messages!

### ISSUE THREAD

**Issue by acodercat** [andersao/l5-repository#474]
like this
```php
class TestRepositoryEloquent extends BaseRepository implements TestRepository
{

    protected $rules = [
        ValidatorInterface::RULE_CREATE => [
            'name' => 'required',
        ],
        ValidatorInterface::RULE_UPDATE => [
            'name' => 'required'
        ]
   ];
    protected $messages = [
        'name.required' => '标题必须填写'
        
    ];
```

**Comment by acodercat** [comment]
in BaseRepository.php validator function  I am add $validator->setMessages($this->messages);
```php
 public function validator()
    {

        if (isset($this->rules) && !is_null($this->rules) && is_array($this->rules) && !empty($this->rules)) {
            if (class_exists('Prettus\Validator\LaravelValidator')) {
                $validator = app('Prettus\Validator\LaravelValidator');
                if ($validator instanceof ValidatorInterface) {
                    $validator->setRules($this->rules);
                    $validator->setMessages($this->messages);
                    return $validator;
                }
            } else {
                throw new Exception(trans('repository::packages.prettus_laravel_validation_required'));
            }
        }

        return null;
    }

```

**Comment by qiutuleng** [comment]
Hi.
you can add the folder of the corresponding language in'resources/lang/'

like this:
![qq 20171114172003](https://user-images.githubusercontent.com/30284139/32772221-2a72c2d8-c960-11e7-9ad8-428f292088db.png)

my language file comes from [caouecs/Laravel-lang](https://github.com/caouecs/Laravel-lang/tree/master/src/zh-CN)

**Comment by acodercat** [comment]
thanks!!!

**Comment by acodercat** [comment]
我要是想把关键字替换成中文怎么办呢，因为我直接把错误显示在客户端，显示英文字段名字的话不太合适

**Comment by qiutuleng** [comment]
like this: [validation.php](https://github.com/caouecs/Laravel-lang/blob/master/src/zh-CN/validation.php#L119-L149)

In `resources/lang/zh/validation.php`
```
return [
    //...

    'attributes' => [
        'attribute' => '属性名',
        'username' => '用户名',
        'email' => ‘邮箱'
        //...
    ]
]
```

**Comment by andersao** [comment]
@acodercat Did your question solved?

**Comment by acodercat** [comment]
yes  thx!  but now i want use ddd.

**Comment by leofelipemendes** [comment]
@andersao 
hi friend, i'm trying translate de messages from de validator class but in this class i can't put the helper trans()
I'm doing like this: 
protected $messages = [
        'cd_unidade_reguladora.required' => trans('messages.cd_unidade_obriga'),
        'cd_unidade_reguladora.integer' => trans('messages.cd_unidade_inteiro')
    ];
but not work.
Have you any suggestion?
tks
