### ISSUE TITLE
Presenter and Events

### ISSUE THREAD

**Issue by ghost** [andersao/l5-repository#48]
When you have to pass a Model to an Event you use `->skipPresenter()`, this causes a problem when you need to Present the data afterwards because you have to get the information from the database again to get it in the correct format. 

Would it be possible to Transform the Model without making a query again?

**Comment by andersao** [comment]
Hello@syflipper ,

Today released a new version of the package with some improvements , including something that can solve your problem ;)

https://github.com/prettus/l5-repository#using-the-presenter-after-from-the-model
