### ISSUE TITLE
Cacheable Repository Interface incompatible with PHP 7.2

### ISSUE THREAD

**Issue by nabeelio** [andersao/l5-repository#483]
PHP 7.2 and above throws a fatal error now when the method signature of a trait doesn't match. See here:

https://travis-ci.org/nabeelio/phpvms/jobs/312778394#L752

The fix itself is pretty simple, I can put a PR in if needed.

**Comment by tianyong90** [comment]
I'm also suffering from the same issue, I found that someone refactored the `paginate` and `simplePaginate` method in BaseRepository on 20 Feb 2016, but the `paginate` method in CacheableRepository Trait has not adjusted  according to the refactoring.

![image](https://user-images.githubusercontent.com/9278461/33805123-55446172-ddee-11e7-8731-3542e178ae30.png)

**Comment by nabeelio** [comment]
I created a small PR to fix that issue. In my project, I created the trait and fixed it and pull that in, instead of the one from the vendor directory

**Comment by eullercdr** [comment]
Fixed in latest release
