### ISSUE TITLE
updaing resulted in two functions having mismatched func arguement

### ISSUE THREAD

**Issue by shez1983** [andersao/l5-repository#484]
PHP Fatal error:  Declaration of Prettus\Repository\Traits\CacheableRepository::paginate($limit = NULL, $columns = Array) must be compatible with Prettus\Repository\Eloquent\BaseRepository::paginate($limit = NULL, $columns = Array, $method = 'paginate') in /home/forge/dev.afleteapp.com/app/Api/V2/Repositories/BaseRepository.php on line 7

so i have manually added ', $method = 'paginate'' to the CacheableRepository::paginate()

**Comment by andersao** [comment]
Solved in Pull Request #487
