### ISSUE TITLE
Validation rule 'in_array'

### ISSUE THREAD

**Issue by DmitryZelonkin** [andersao/l5-repository#486]
Hi guys!

How I can add rule 'in_array' in my Validator class? I try:

'level'          => 'required|string|in_array:' . App\Model\Vacancy::LEVELS,

But it's not worked.

Thanks for your answer.

**Comment by mCassy** [comment]
@DmitryZelonkin try
`'level' => 'required|string|in:' .implode(',', App\Model\Vacancy::LEVELS),`
