### ISSUE TITLE
json_encode() has problem

### ISSUE THREAD

**Issue by heshiweij** [andersao/l5-repository#498]
I write API for Android/ios app using l5-repo. 

```
$orders = $this->shopVisitOrderRepository->paginate(); 
$jsonStr = json_encode($order)
```
The meta in $jsonStr at first page (?page=1) as follow:
```
 "meta": {
            "pagination": {
                "total": 70,
                "count": 15,
                "per_page": 15,
                "current_page": 1,
                "total_pages": 5,
                "links": {
                    "next": "https://huanjv.dev/api/o2o/o2o/list?page=2"
                }
            }
        }
```

but there are only one page, so meta in $jsonStr is:
```
 "meta": {
            "pagination": {
                "total": 6,
                "count": 6,
                "per_page": 15,
                "current_page": 1,
                "total_pages": 1,
                "links": []
            }
  }
```

for app(Android), links  [] or {} is  totally different。 
The source of this problem is: json_encode(), we could use argument JSON_FORCE_OBJECT to resolve it.

but, l5-repo don't provider argument for paginate() method.  
I very expect ...

**Comment by andersao** [comment]
Hi @heshiweij, are you using the `league/fractal` package? 
What version of `l5-repositoy` you are using?

**Comment by andersao** [comment]
@heshiweij, this is issue of [`Fractal`](http://fractal.thephpleague.com). You can resolve or manipulate that using a Custom [`Serializer`](http://fractal.thephpleague.com/serializers/) of [Fractal](http://fractal.thephpleague.com) like this.

```php
<?php

namespace App\Serializer;

use League\Fractal\Pagination\PaginatorInterface;
use League\Fractal\Serializer\ArraySerializer;

class CustomDataApiSerializer extends ArraySerializer {

    public function paginator(PaginatorInterface $paginator)
    {
        $meta = parent::paginator($paginator);

        // here your would manipulate the pagination data
        if( empty($meta["pagination"]["links"]) ){
            $meta["pagination"]["links"] = [
                "next" => null
            ];
        }

        return $meta;
    }
}
```

then in your `config\repository.php`, set your new serialize in 

```php
'fractal'    => [
        ...
        'serializer' => \App\Serializer\CustomDataApiSerializer::class
    ],
```

I hope that I was help you.
