### ISSUE TITLE
Model with identity type is string.

### ISSUE THREAD

**Issue by djdd1203** [andersao/l5-repository#534]
I create model with identity type is string and when I call all method, identity field in this table always return 0. I think have that code convert to integer but I can't find it.
How to fix that error? Please help me.

**Comment by johannesschobel** [comment]
can you please clarify the actual issue and describe the problem? Not sure if i understand it correctly..

Be sure to have the `laravel migration` file correctly set up and do not manually `cast` the string to integer in the model (`protected $casts`)

**Comment by monsterddq** [comment]
thanks @johannesschobel, this problem is fix.
