### ISSUE TITLE
Qual a diferença entre Presenter e Transformer, como se usa?

### ISSUE THREAD

**Issue by eumanito** [andersao/l5-repository#547]
Observei que o Presenter só chama o Transformer. O que mais posso fazer no Presenter? Tem documentação ou exemplos?

O Transformer tem o método transform() que retornar um array dos campos, então posso manipular algum campo no momento da consulta? Porém é necessário listar nesse array todos os campos mesmo que não sejam manipulados?

**Comment by renanBritz** [comment]
O que compreendo é o seguinte:

A ideia é você não retornar nada relacionado ao Eloquent dos repositórios para evitar acoplamento. Para isso você "apresenta" os dados de forma padronizada, sendo um array ou objeto do domínio. E para fazer isso é necessário "transformar" esses dados. Exemplo: mapear Pessoa em um array.

Os dados obtidos usando o presenter devem ser usados apenas para leitura. Toda a lógica de persistência deve ficar no repositório.

Abraço!

**Comment by eumanito** [comment]
Obrigado @renanBritz!
E é necessário listar nesse array todos os campos mesmo que não sejam manipulados? Achei ruim pois quando preciso incluir ou remover algum campo no banco de dados é necessário alterar a Model, o Repository, o Controller, a Migration e agora, também, o Transform com Presenter. É assim mesmo ou estou enganado?

**Comment by renanBritz** [comment]
Você precisa listar os campos que serão, por exemplo, retornados em uma API, ou usados para a lógica de negócio em um controlador. Ou seja, não necessariamente precisam ser todos.

Caso não queira usar presenters, você pode também usar a seguinte sintaxe:

```php
public function show(PersonRepository $repo)
{
    $person = $repo->skipPresenter()->find(1); // Retorna Person (Model)
}
```

Nesse caso, meu **controlador** estaria trabalhando com um objeto Model, que é uma dependência com baixa abstração. Tornando-o pouco flexível e difícil de sofrer grandes mudanças no futuro, como a de trocar de ORM, o que raramente ocorre em um projeto, ironicamente...

**Comment by eumanito** [comment]
Entendi. Obrigado @renanBritz.
