### ISSUE TITLE
using Presenter: skip "data" array level from output ?

### ISSUE THREAD

**Issue by pat-och** [andersao/l5-repository#554]
_php 7.0.23
laravel 5.5.42
league/fractal: ^0.17.0
prettus/l5-repository: ^2.6_

is there a relative simple way to have basic l5-repository coupled with presenter/transformer returning a simple array without the "data"level ?

**below what is achieved** with `$this->myEntityRepository->all()`
```
array:1 [▼
  "data" => array:10 [▼
    0 => array:6 [▶]
    1 => array:6 [▶]
    2 => array:6 [▶]
  ]
]
```

**Expected**, obtained with `$this->myEntityRepository->all()['data']`
```
array:10 [▼
  0 => array:6 [▶]
  1 => array:6 [▶]
  2 => array:6 [▶]
]
```

like that, in my code, i can use a beautiful `$this->myEntityRepository->all()` where what happens behind is completely transparent to the user
instead of the ugly `$this->myEntityRepository->all()['data']`

_fyi, the standart behavior, with data level, makes fail this_
`DataTables::of($this->myEntityRepository->all())`
_whereas the ugly line make its worked_

_**PS**
Ideally, I'd like to have a laravel collection filled with stdclass in return, but this goal is a whole other ball game:-)_

**Comment by pat-och** [comment]
duplicated with https://github.com/andersao/l5-repository/issues/107
So seems we need to write own serializer to handle this

**Comment by pat-och** [comment]
**the right answer is:**
in published config/repository.php
change `serializer' => league\Fractal\Serializer\DataArraySerializer::class`
by `serializer' => league\Fractal\Serializer\ArraySerializer::class`
_(so no need to make own serializer for this purpose)_
```
    /*
    |--------------------------------------------------------------------------
    | Fractal Presenter Config
    |--------------------------------------------------------------------------
    |

    Available serializers:
    ArraySerializer
    DataArraySerializer
    JsonApiSerializer

    */
    'fractal'    => [
        'params'     => [
            'include' => 'include'
        ],
        'serializer' => league\Fractal\Serializer\ArraySerializer::class
    ],
```
IMPORTANT don't forget to run `php artisan config:clear` or `php artisan config:cache` to access your new config

**Comment by eleftrik** [comment]
Why has this issue been closed?
Presenter is still returning `data`.
Thanks

**Comment by mirucon** [comment]
Simply create a serializer class like this to get collections without "data" key.

```php
/**
 * @see     https://github.com/thephpleague/fractal/issues/315
 *
 * @package App\Serializers
 */
class SimpleArraySerializer extends ArraySerializer
{
    /**
     * Serialize a collection without "data" key.
     *
     * @param string $resourceKey
     * @param array  $data
     *
     * @return array
     */
    public function collection($resourceKey, array $data)
    {
        return $data;
    }
}
````

Then in `config/repository.php`, specify this class as a serializer.

**Comment by eleftrik** [comment]
Thank you @mirucon, I implemented a class like yours.

**Comment by tdchien** [comment]
Hi
Thank for your idea. I'm having a concert with the way to change serialize of Fractal.
Does someone could let me know how to do if I just want change serialize of a includes.
There is example with **comments** relationship

```
array:1 [▼
  "data" => array:10 [▼
    0 => array:6 [
           "first_name": "",
           "last_name": "",
           "comments": [▼
                 "data": [
                        array:3[▼],
                        array:3[▼]
                  ]
            ],
    ]
    1 => array:6 [▶]
    2 => array:6 [▶]
  ]
]
```

**Expected**
```
array:1 [▼
  "data" => array:10 [▼
    0 => array:6 [
           "first_name": "",
           "last_name": "",
           "comments": [▼
                 array:3[▼],
                 array:3[▼]
            ],
    ]
    1 => array:6 [▶]
    2 => array:6 [▶]
  ]
]
```
