### ISSUE TITLE
map search field

### ISSUE THREAD

**Issue by jebraieili** [andersao/l5-repository#556]
Hi
How can map search field like:
api.domain.develop/endpoint?search=title:keyword

protected $fieldSearchable = [
  'd_vch_title' => 'like',
];

**Comment by mCassy** [comment]
You can substitute d_vch_title with title in request.Something like:
`$request->merge(['title'=>$request->get('d_vch_title')]);`

**Comment by mCassy** [comment]
mb try to re-create $request object: 
`$request = new \Illuminate\Http\Request($request->all());
$request->merge(['title' => $request->get('d_vch_title')]);
`
This should work I think...

**Comment by jebraieili** [comment]
Unfortunately, it did not work again.
i use apiato project (https://github.com/apiato/apiato ) and this use l5-repository.
