### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by hiddeco** [andersao/l5-repository#56]
This package has no tests at all. I think that it is crucial for a good package to have extensive tests.

I also think it would be beneficial to add them as soon as possible. There will be more features in this package soon and more features will only mean more tests to write.

**Comment by Jeroen-G** [comment]
See #42

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
