### ISSUE TITLE
Error while using RequestCriteria with yajra/laravel-datatables (Server-Side)

### ISSUE THREAD

**Issue by khalilcharfi** [andersao/l5-repository#567]
ErrorException (E_WARNING)
stripos() expects parameter 1 to be string, array given

`protected function parserSearchData($search)
    {
        $searchData = [];
 
        if (stripos($search, ':')) {
            $fields = explode(';', $search);
 
            foreach ($fields as $row) {
                try {
                    list($field, $value) = explode(':', $row);
                    $searchData[$field] = $value;
                } catch (\Exception $e) {
                    //Surround offset error
                }
            }
        }
 
        return $searchData;
    }`

**Comment by khalilcharfi** [comment]
I found a quick (not clean) solution.
Well, the problem was that the 'datatables' ajax request has the same query key "search=" .
So the solution was to change this line in the RequestCriteria class:
`$search = $this->request->get(config('repository.criteria.params.search', 'search'), null);`

to

`$search = $this->request->get(config('search1', 'search1'), null);`

**Comment by macagoraga** [comment]
in repository config you can change search params to something else , line 213
