### ISSUE TITLE
Add new to BaseRepository

### ISSUE THREAD

**Issue by tomocy** [andersao/l5-repository#570]
I think that it is better to add a method "new(array $attributes = [])" to BaseController to return new Entity.
In Laravel, the save method of eloquent relationships is often used to add models to relationships.
eg)

```
$user->posts()->save(new Post());
```

l5-repository already has firstOrNew but this method cannot do, for example, add a new post model which has the same attributes as a post record in db to relationships of a user because it returns the post model in db not new post model.

if the new method is added, it is possible to do the followings.

```
$user->posts()->save($this->repository->new(['content' => 'hello world']));
```

What do you think?

**Comment by Owen-oj** [comment]
You can do this 
`$user->posts()->create(['content'=> 'Hello])`
The only difference between `save` and `create` is `save` accepts full Eloquent model Instance whiles `create` accepts an array of atttributes. 
 Check from the  [Laravel Website](https://laravel.com/docs/5.5/eloquent-relationships#the-create-method).

**Comment by tomocy** [comment]
That's right.
I persisted

**Comment by tomocy** [comment]
That's right.
I persisted in using repository pattern in controllers.
Thanks.
