### ISSUE TITLE
Does not support lumen 5.7?

### ISSUE THREAD

**Issue by mrzxy** [andersao/l5-repository#585]
![image](https://user-images.githubusercontent.com/11501927/51458993-04888f80-1d92-11e9-917f-8ea948cda9e1.png)
![image](https://user-images.githubusercontent.com/11501927/51459013-0f432480-1d92-11e9-9bb6-ef9f9f1329ea.png)

**Comment by gsi-alejandro** [comment]
It does not work for me in Lumen 5.7 either, it's a pity because it's a very complete library and it provides many facilities for the development of solutions. 

Please ask them to give an answer as soon as possible about what the problem might be and its possible solution.

**Comment by mrzxy** [comment]
You must set up `$app->withEloquent()`
