### ISSUE TITLE
😢 how to use aliases in search

### ISSUE THREAD

**Issue by id1385** [andersao/l5-repository#589]
hi
my query is : 

`SELECT cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR ' > ' ) AS name, c1.parent_id, c2.sort_order FROM category_path cp LEFT JOIN category c1 ON ( cp.category_id = c1.category_id ) LEFT JOIN category c2 ON ( cp.path_id = c2.category_id ) where c1.name <> '' GROUP BY c1.category_id ORDER BY NAME ASC`

**i want search with c1.name 
c1 is alias of tb category that joined**

my $fieldSearchable of CategoryRepository is : 
`

    protected $fieldSearchable = [
        'category_id',
        'name' => 'like'
    ];
`
and my query function is : 

`return $this->repository->scopeQuery(function ($query) use ($data) {
            return $query->select(DB::raw('cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR " > " ) AS name, c1.parent_id, c2.sort_order,c1.image'))
                ->from('category_path as cp')
                ->leftJoin('category as c1', 'cp.category_id', '=', 'c1.category_id')
                ->leftJoin('category as c2', 'cp.path_id', '=', 'c2.category_id')
                ->where('c2.name', '<>', null)
                ->groupBy('cp.category_id')
                ->orderBy('name')
                ->limit(10);
        })->all();`

this work success but when i send search query param like ?search=name:test
its want to query for category.name that not exist and return error 
error : 
`
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.name' in 'where clause' (SQL: select cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR \" > \" ) AS name, c1.parent_id, c2.sort_order,c1.image from `category_path` as `cp` left join `category` as `c1` on `cp`.`category_id` = `c1`.`category_id` left join `category` as `c2` on `cp`.`path_id` = `c2`.`category_id` where (`category`.`name` like %test%) and `c2`.`name` is not null group by `cp`.`category_id` order by `name` asc limit 10)
`

**so how can do search in aliased columns  ?**

**Comment by dev2552** [comment]
> hi
> my query is :
> 
> `SELECT cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR ' > ' ) AS name, c1.parent_id, c2.sort_order FROM category_path cp LEFT JOIN category c1 ON ( cp.category_id = c1.category_id ) LEFT JOIN category c2 ON ( cp.path_id = c2.category_id ) where c1.name <> '' GROUP BY c1.category_id ORDER BY NAME ASC`
> 
> **i want search with c1.name c1 is alias of tb category that joined**
> 
> my $fieldSearchable of CategoryRepository is :
> `
> 
> ```
> protected $fieldSearchable = [
>     'category_id',
>     'name' => 'like'
> ];
> ```
> 
> `
> and my query function is :
> 
> `return $this->repository->scopeQuery(function ($query) use ($data) { return $query->select(DB::raw('cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR " > " ) AS name, c1.parent_id, c2.sort_order,c1.image')) ->from('category_path as cp') ->leftJoin('category as c1', 'cp.category_id', '=', 'c1.category_id') ->leftJoin('category as c2', 'cp.path_id', '=', 'c2.category_id') ->where('c2.name', '<>', null) ->groupBy('cp.category_id') ->orderBy('name') ->limit(10); })->all();`
> 
> this work success but when i send search query param like ?search=name:test
> its want to query for category.name that not exist and return error
> error :
> `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.name' in 'where clause' (SQL: select cp.category_id AS category_id, GROUP_CONCAT( c2.NAME ORDER BY cp.LEVEL SEPARATOR \" > \" ) AS name, c1.parent_id, c2.sort_order,c1.image from`category_path`as`cp`left join`category`as`c1`on`cp`.`category_id`=`c1`.`category_id`left join`category`as`c2`on`cp`.`path_id`=`c2`.`category_id` where (`category`.`name`like %test%) and`c2`.`name`is not null group by`cp`.`category_id`order by`name`asc limit 10)`
> 
> **so how can do search in aliased columns ?**

**Comment by sdjrppl** [comment]
+1
