### ISSUE TITLE
With method is not working correctly. Too many queries.

### ISSUE THREAD

**Issue by bddimitrov** [andersao/l5-repository#595]
With method is generating too many queries. It's making query for every single row.

For example:

This is generating 6 queries:

`$diet = Diet::with('days', 'days.meals', 'days.meals.items', 'days.meals.items.food')->find(2);`

And repo is generating 106:
`$diet = $this->repository
                     ->with('days', 'days.meals', 'days.meals.items', 'days.meals.items.food')
                     ->find($id);`

100 more queries, this is overkill.

**Comment by catalin125** [comment]
Hi! I think your method doesnt work at all.
When you have multiple relations, you should use the 'with' method with an array given.
Example: $this->repository->with( ['day', 'days.meal'] )->find($id);

**Comment by bddimitrov** [comment]
Yep, I just found how stupid I am. Thank you. The problem was that i was not using array.

**Comment by catalin125** [comment]
It happens.. Have a nice day! :)

**Comment by ajayinfyom** [comment]
@bddimitrov I think you need to close this issue.
it's a good thing if anyone creates any issue on any repo than you realize that its not really issue/bug or find a solution than a close that issue.

**Comment by fengliang2011** [comment]
$medicine = $this->medicine
            ->with([
                'favorites' => function ($query) use ($user) {
                    $query->where('user_id', $user->id);
                }
            ])
            ->where('uuid', $uuid)
            ->firstOrFail();

the favorites Closure does not work
