### ISSUE TITLE
why phpstorm show error when using pushCriteria ? [file attached]

### ISSUE THREAD

**Issue by id1385** [andersao/l5-repository#601]
![error](https://user-images.githubusercontent.com/28746285/56015829-98258880-5d0f-11e9-8ed2-785e2b82e65a.png)

please see image

**Comment by id1385** [comment]
fixed when i put this comment above function

`    /**
     * @param Request $request
     * @return mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */`

**Comment by id1385** [comment]
But I still do not know why the error is showing
_What is the relationship with Phpdoc?_

**Comment by clegginabox** [comment]
It's showing an error because `pushCriteria` could potentially throw an exception that you are not catching
