### ISSUE TITLE
deleteWhere In Not Working

### ISSUE THREAD

**Issue by id1385** [andersao/l5-repository#605]
> `$this->repository->deleteWhere([
            ["attribute_id" ,"in", [19,21,20]]
        ]);
`

why this method not work and return below query

> delete from `attribute` where `attribute_id` = 'in'

i want delete multi row

**Comment by vikashsp** [comment]
Correct format supported currently is:
Delete entry in Repository by multiple fields
```
$this->repository->deleteWhere([
    //Default Condition =
    'state_id'=>'10',
    'country_id'=>'15',
])
```

**Comment by id1385** [comment]
> Correct format supported currently is:
> Delete entry in Repository by multiple fields
> 
> ```
> $this->repository->deleteWhere([
>     //Default Condition =
>     'state_id'=>'10',
>     'country_id'=>'15',
> ])
> ```
> Ref. [Documentation](https://github.com/andersao/l5-repository#prettusrepositorycontractsrepositoryinterface)

thanks But i want use **Where In**  in my query
document not ref for this item

i tried to change default condition but get error !

> `$this->repository->deleteWhere([ ["attribute_id" ,"in", [19,21,20]] ]);`

**Comment by alexkopytov** [comment]
> > Correct format supported currently is:
> > Delete entry in Repository by multiple fields
> > ```
> > $this->repository->deleteWhere([
> >     //Default Condition =
> >     'state_id'=>'10',
> >     'country_id'=>'15',
> > ])
> > ```
> > 
> > 
> > Ref. [Documentation](https://github.com/andersao/l5-repository#prettusrepositorycontractsrepositoryinterface)
> 
> thanks But i want use **Where In** in my query
> document not ref for this item
> 
> i tried to change default condition but get error !
> 
> > `$this->repository->deleteWhere([ ["attribute_id" ,"in", [19,21,20]] ]);`

@id1385  Have same problem, are you found solution?
