### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by saulo-silva** [andersao/l5-repository#613]
Last Update 4 Feb 2018
Pull request *41*

**Comment by pvmerlo** [comment]
Nah.

**Comment by saulo-silva** [comment]
Ops!

**Comment by lorvent** [comment]
this is one of the popular packages for laravel.

so it would be sad to hear...if project is abandoned

**Comment by lloricode** [comment]
maybe, 


Version | Release | Bug Fixes Until | Security Fixes Until
-- | -- | -- | --
5.5 (LTS) | August 30th, 2017 | August 30th, 2019 | August 30th, 2020
5.6 | February 7th, 2018 | August 7th, 2018 | February 7th, 2019
5.7 | September 4th, 2018 | March 4th, 2019 | September 4th, 2019
5.8 | February 26th, 2019 | August 26th, 2019 | February 26th, 2020
6.0 (LTS) | September 3rd , 2019 | September 3rd, 2021 | September 3rd, 2022


this tuesday, laravel 6 will release with LTS support, then this repo is not supported if you look in [composer.json](https://github.com/andersao/l5-repository/blob/master/composer.json#L23-L29)

I've already send [PR](https://github.com/andersao/l5-repository/pull/616) to laravel 5.8 compatibility, but its not merge yet

**Comment by lloricode** [comment]
i made a new inspired with this, but its private package because i make it inside of company i work in, i have not much time to implement as personal to make it open source

**Comment by Yannik-Slym** [comment]
@felipefrancioni may be this one : https://github.com/rinvex/laravel-repositories

**Comment by lloricode** [comment]
@Yannik-Slym it is has a api integration? like search? in query parameter?

**Comment by lorvent** [comment]
that may be alternative but i don't see much activity there aswell so i am skeptical about that one too.

**Comment by amirhs712** [comment]
> that may be alternative but i don't see much activity there aswell so i am skeptical about that one too.

I hope it's not abandoned by the author, but if it is, I think it would be a good idea to fork it and continue the great work.

**Comment by khairilanuar** [comment]
Hi guys, Laravel 6.0 is coming. I really love this package but since it is not compatible with Laravel 6.0, maybe we can together maintain it as a fork.

I forked this project at https://github.com/khairilanuar/laravel-repository and it is currently able to work with Laravel 6.0.

hope we can all work together to maintain this fork.

thank you,
- Khairil

**Comment by saulo-silva** [comment]
44 pull request open.
https://github.com/andersao/l5-repository/pulls

Copy???

> Hi guys, Laravel 6.0 is coming. I really love this package but since it is not compatible with Laravel 6.0, maybe we can together maintain it as a fork.
> 
> I forked this project at https://github.com/khairilanuar/laravel-repository and it is currently able to work with Laravel 6.0.
> 
> hope we can all work together to maintain this fork.
> 
> thank you,
> 
> * Khairil

**Comment by eullercdr** [comment]
Dear, please, indicate to me PRs that you see greater value. I will try to help keep the repository alive. I have now added compatibility with laravel 6!

**Comment by lloricode** [comment]
@eullercdr thanks for merging ☺️

**Comment by lloricode** [comment]
maybe can we close this issue?
this is now compatible with coming laravel 6 :100:

**Comment by lloricode** [comment]
https://github.com/andersao/l5-repository/releases

**Comment by saulo-silva** [comment]
> Dear, please, indicate to me PRs that you see greater value. I will try to help keep the repository alive. I have now added compatibility with laravel 6!

Merge this PR:
https://github.com/andersao/l5-repository/pull/594
https://github.com/andersao/l5-repository/pull/602

Suggestions to merge PR urgent?

**Comment by khairilanuar** [comment]
Hi @eullercdr,

I submitted new pull request to make generator command works with Laravel 6.0 https://github.com/andersao/l5-repository/pull/625

appreciate if you can have a look

many thanks,
- Khairil

**Comment by lloricode** [comment]
hi @eullercdr , this is already released, but the https://packagist.org/packages/prettus/l5-repository not updated so we cant get the latest release

**Comment by cunio-martin** [comment]
same problem here, @eullercdr can you check that?

**Comment by eullercdr** [comment]
Everything is ok now. The packlist was changed!!

**Comment by lorvent** [comment]
@eullercdr still there is a problem because it depends on prettus/larave-validation which still using having laravel 5.x dependencies.

i guess there is a PR already for it, would be great if you can merge that and release a new version.

thanks.

**Comment by eullercdr** [comment]
@lorvent  please send me a PR for solve that. This change will affect the users that are using Laravel 5.x?

**Comment by lorvent** [comment]
@eullercdr there already a PR available https://github.com/andersao/laravel-validator/pull/35

pls check that.

given a chance, i would bump major version and make it available only for laravel 6.x but that PR also serves the need for now.

**Comment by MatheusNaldi** [comment]
> maybe,
> 
> Version	Release	Bug Fixes Until	Security Fixes Until
> 5.5 (LTS)	August 30th, 2017	August 30th, 2019	August 30th, 2020
> 5.6	February 7th, 2018	August 7th, 2018	February 7th, 2019
> 5.7	September 4th, 2018	March 4th, 2019	September 4th, 2019
> 5.8	February 26th, 2019	August 26th, 2019	February 26th, 2020
> 6.0 (LTS)	September 3rd , 2019	September 3rd, 2021	September 3rd, 2022
> this tuesday, laravel 6 will release with LTS support, then this repo is not supported if you look in [composer.json](https://github.com/andersao/l5-repository/blob/master/composer.json#L23-L29)
> 
> I've already send [PR](https://github.com/andersao/l5-repository/pull/616) to laravel 6 compatibility, but its not merge yet

Your PR doesn't make this package compatible with laravel 6, there is a lot of changes to do, this package doesn't even have compatibility with laravel 5.8, things like TTL of cache have been changed to seconds instead of minutes, there is a PR opened about that but it wasn't merged.
