### ISSUE TITLE
How to use findWhere combine with findWhereIn?

### ISSUE THREAD

**Issue by kimprosh** [andersao/l5-repository#620]
I want to use findWhere combine with findWhereIn in repository but I can't. How to do it?
conditions:

```
'field_a' = 'a' AND 'field_b' IN ('b', 'c', 'd')
```

**Comment by Minotti** [comment]
Hey, i created on my project one solution like this, but, i didn't use scope.
Scope is very quickly and easy for only just small problem, but, imagine this situation in many parts of the project.

I created one trait (NewsOnRepositorie) and use her in my Repository.
On trait have this:

```
public function whereIn($field, array $values)
    {
        $this->applyCriteria();
        $this->applyScope();

        $model = $this->model->whereIn($field, $values);

        $this->resetModel();
        return $this->parserResult($model);
    }
```
And now, just call 

> $this->repository->whereIn($field_a, $array_values_field_b)->...

On **...** is Eloquent Methods, use as u need.

With Trait i have created other methods like **limit**, **whereBetween**

**Comment by guicunha** [comment]
Great solution too

**Comment by kimprosh** [comment]
Thanks @Minotti !
