### ISSUE TITLE
latest versions/tags are not being updated at packagist

### ISSUE THREAD

**Issue by lorvent** [andersao/l5-repository#628]
please have a look

https://packagist.org/packages/prettus/l5-repository

because of that....we are still not able to use 2.6.35 thus can not use it for laravel 6

**Comment by eullercdr** [comment]
Everything is ok now. Please test! :-D

**Comment by lorvent** [comment]
Great 👍

**Comment by lorvent** [comment]
Hello,

eventhough this is fixed, still we can't install it on laravel6
because it depends on https://github.com/andersao/laravel-validator which requires laravel 5.x

so kinda stuck at updating.

hope you can update that package constraints aswell.

**Comment by lesterchan** [comment]
Looks like someone created a PR https://github.com/andersao/laravel-validator/pull/35 on the other repo.

**Comment by lorvent** [comment]
@eullercdr please have a look again at this issue.

thanks.

**Comment by eullercdr** [comment]
Fix, please check this!

**Comment by lorvent** [comment]
@eullercdr still this doesn't work because of this https://github.com/andersao/l5-repository/blob/master/composer.json#L30

so you need to change it to 1.2.* or something like that and release a new version...

**Comment by eullercdr** [comment]
@lorvent please, send me a PR, keep the compatibility with version 1.1 and 1.2. Thanks a lot
