### ISSUE TITLE
Paginate with query

### ISSUE THREAD

**Issue by davepgreene** [andersao/l5-repository#63]
Hi,

Right now there doesn't seem to be a way to get paginated results either after a query (ex. ```$repo->find(1)->paginate()```) or via Fractal.

If this is actually possible, can you provide a little more documentation on how to do it? Otherwise, this would be a great feature to add.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
