### ISSUE TITLE
Installation failed in Laravel 6.0.3

### ISSUE THREAD

**Issue by Jenishpaghadar** [andersao/l5-repository#633]
Your requirements could not be resolved to an installable set of packages.

Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].
    - Installation request for prettus/laravel-validation 1.1.* -> satisfiable by prettus/laravel-validation[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5].

Unable to install  dependency package prettus/laravel-validation also.

Is there solution to install it in current Laravel version.

**Comment by eullercdr** [comment]
@Jenishpaghadar i will look that.

**Comment by eullercdr** [comment]
@Jenishpaghadar try again please, let me know about any error. Thanks

**Comment by Jenishpaghadar** [comment]
@eullercdr I am still getting same error on installation. Thanks

**Comment by eullercdr** [comment]
@Jenishpaghadar try again please.

**Comment by Jenishpaghadar** [comment]
@eullercdr I am able to install it. thanks for help
