### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by binalfew** [andersao/l5-repository#64]
I wonder how would one be confident using this package without some concrete tests. You guys should think about it!!

**Comment by Jeroen-G** [comment]
See #42

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
