### ISSUE TITLE
Call to undefined function Prettus\Repository\Generators\Commands\snake_case() 

### ISSUE THREAD

**Issue by herberjackson** [andersao/l5-repository#658]
laravel 6

**Comment by eleftrik** [comment]
`Call to undefined function Prettus\Repository\Generators\Commands\snake_case()`
in file
`src/Prettus/Repository/Generators/Commands/RepositoryCommand.php:69`

`'name'   => 'create_' . snake_case(str_plural($this->argument('name'))) . '_table'`

**Comment by eleftrik** [comment]
Temporary workaround:
* create a file `app/Helpers/helpers.php` with this content

```
<?php

function snake_case($s)
{
    return \Illuminate\Support\Str::snake($s);
}

function str_plural($s)
{
    return \Illuminate\Support\Str::plural($s);
}

function str_contains($haystack, $needles)
{
    return \Illuminate\Support\Str::contains($haystack, $needles);
}

```

* in `composer.json`, add this file inside "autoload" > "files" section

    "autoload": {
        "files": [
            "app/Helpers/helpers.php"
        ]
    },

* run `composer dump-autoload`

I know this isn't a great solution, but at least you can launch commands such as `php artisan make:repository MyRepository`.

**Comment by mattford** [comment]
Alternative workaround is to install the `laravel/helpers` package which adds all the helpers back from 5.8

Will create a pr shortly to update these function calls to use the classes directly

**Comment by bsormagec** [comment]
Fixed
