### ISSUE TITLE
Make Generator Class Paths Configurable

### ISSUE THREAD

**Issue by chrisvanderpoel** [andersao/l5-repository#68]
As it stands now, generators provide little flexibility in how we store our generated classes within our application.  We, for instance, store our models in `Models` directory, our repository interfaces under `Contracts` and our repositories under `Repositories`.  It would also be nice to provide us a way to specify where transformations and presenters were stored as well.

This could easily be accomplished through configuration.  Perhaps something like this...

```php
'paths' => [
    'models' => 'Models',
    'repositories' => 'Repositories/Eloquent',
    'interfaces' => 'Contracts/Repositories',
    'transformers' => 'Transformers',
    'presenters' => 'Presenters'
]
```

... along with some slight modification made to the stubs to accommodate the `use` paths.

**Comment by chrisvanderpoel** [comment]
Created a pull request for this.

https://github.com/prettus/l5-repository/pull/69

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
