### ISSUE TITLE
Support For Laravel 7

### ISSUE THREAD

**Issue by lesterchan** [andersao/l5-repository#693]
Any plans to support Laravel 7?

**Comment by tiagoferezin** [comment]
> Any plans to support Laravel 7?
Yes, on commit 7194cb4 waiting merge of pull request https://github.com/andersao/l5-repository/pull/694/

**Comment by lucasantoniooficial** [comment]
Does not install on Laravel 7.0.5, I even tried with dev-master

**Comment by tiagoferezin** [comment]
It is not installing on any version of Laravel 7.x, @andersao please release the pull request https://github.com/andersao/l5-repository/pull/694

**Comment by lesterchan** [comment]
@lucasantoniooficial that is because the PR has not been merged yet.

**Comment by clipvui2512** [comment]
wating for long time :(

**Comment by tiagoferezin** [comment]
#695

**Comment by tiagoferezin** [comment]
https://github.com/andersao/l5-repository/commit/7194cb4c9cb50005914eb4ff9d8055b30cd14222

**Comment by lorvent** [comment]
its more than a week and i hope devs release new version with support for v7

if not, i hope someone would fork it and maintain a package till original author readies the package.

**Comment by bsormagec** [comment]
Fixed now.
