### ISSUE TITLE
Does not install on laravel 7.0.5

### ISSUE THREAD

**Issue by lucasantoniooficial** [andersao/l5-repository#695]
No illuminate / filesystem installation error, error message:

 

> - don't install illuminate/filesystem v5.6.21|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.22|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.23|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.24|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.25|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.26|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.27|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.28|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.29|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.3|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.30|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.31|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.32|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.33|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.34|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.35|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.36|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.37|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.38|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.39|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.4|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.5|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.6|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.7|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.8|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.6.9|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.0|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.1|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.10|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.11|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.15|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.2|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.20|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.21|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.22|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.23|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.26|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.27|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.28|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.3|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.4|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.5|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.6|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.7|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.8|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.7.9|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.0|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.11|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.12|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.14|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.15|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.17|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.18|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.19|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.2|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.20|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.22|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.24|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.27|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.28|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.29|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.3|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.30|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.31|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.32|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.33|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.34|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.35|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.36|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.4|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.8|don't install laravel/framework v7.0.5
>     - don't install illuminate/filesystem v5.8.9|don't install laravel/framework v7.0.5
>     - Installation request for laravel/framework (locked at v7.0.5, required as ^7.0) -> satisfiable by laravel/framework[v7.0.5].
> 

I tested newer version, dev-master and dev-develop

**Comment by tiagoferezin** [comment]
#693

**Comment by tiagoferezin** [comment]
Pull request https://github.com/andersao/l5-repository/pull/694

**Comment by redbonzai** [comment]
Please deploy the release for Laravel 7.0 compatibility.

**Comment by tiagoferezin** [comment]
#Closed in commit https://github.com/andersao/l5-repository/commit/7194cb4c9cb50005914eb4ff9d8055b30cd14222

**Comment by dhsont** [comment]
@acasey , @tiagoferezin 

There is still issue while installing on laravel 7 

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - prettus/l5-repository 2.6.9 requires prettus/laravel-validation 1.1.* -> satisfiable by prettus/laravel-validation[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1
.4, 1.1.5] but these conflict with your requirements or minimum-stability.
 ```

please update supported prettus/laravel-validation version to dev-master 
``` "prettus/laravel-validation": "~1.1|~1.2"```
or 
add laravel 7 support to  prettus/laravel-validation: ~1.2

**Comment by VVlasy** [comment]
temporary solution is using the below in composer.json
`"prettus/laravel-validation": "dev-master as 1.2.0",`

**Comment by bsormagec** [comment]
Fixed now.
