### ISSUE TITLE
Collaborator/clean up prs & issues

### ISSUE THREAD

**Issue by dubcanada** [andersao/l5-repository#698]
Hello @andersao 

I want to help clean up the PRs and fix a few issues. Could you make me a collaborator?

Thanks,

**Comment by lorvent** [comment]
I am interested aswell
if not, i will try to maintain a fork of the repo with upto date dependencies.

**Comment by dubcanada** [comment]
I am going to maintain a fork at https://github.com/dubcanada/l5-repository

So far I've removed the validator components as FormRequest handles it the same way, I will be making a few more edits, it can be installed with `"dubcanada/l5-repository": "dev-master"`

**Comment by bsormagec** [comment]
Everything good now.
