### ISSUE TITLE
Serialization of 'ReflectionProperty' is not allowed

### ISSUE THREAD

**Issue by profikart** [andersao/l5-repository#704]
Hi,
I have error when i'm using PHP 7.4.4

message	"Serialization of 'ReflectionProperty' is not allowed"
exception	"Exception"
file	"/home/marcin/public_html/panelv3/vendor/prettus/l5-repository/src/Prettus/Repository/Traits/CacheableRepository.php"
line	147

**Comment by lloricode** [comment]
same issue

**Comment by asteiman** [comment]
Exactly the same
