### ISSUE TITLE
JWTAuth::attempt with tymondesigns / jwt-auth always return false.

### ISSUE THREAD

**Issue by latuconsinafr** [andersao/l5-repository#708]
Hello,

I got an error using tymondesigns/jwt-auth on JWTAuth::attempt method which always return false eventhough the email and the password is do match. 
After a moment of tracing back the error, i got a conclusion if the user creation via repository->create() lead to this error, while the user creation via conventional way like user = new User() and so is success.

Is there any way out to combine the tymondesigns/jwt-auth with this repository pattern? Thank you.

**Comment by bsormagec** [comment]
I think its not about this package you are doing wrong something. Dont do User auth's from repository pattern.
