### ISSUE TITLE
Event handling ?

### ISSUE THREAD

**Issue by DarKDinDoN** [andersao/l5-repository#72]
Hello,

So in you package, you fire some events when the model is updated, deleted or created.

Example :
A random model is updated. The repository fire an event : RepositoryEntityUpdated.
But what if the listener should have a different response depending on the action ?
Maybe, I want to send an email when the "status" attribute is modified and a different one, when the "type" attribute is modified.
Maybe, I want to fire an event depending on the route.

But the listener always catch the same event right ? (RepositoryEntityUpdated)

So is there any clean solution here ? Or do we have to fire our own events ?

Thanks,

**Comment by yajra** [comment]
+1. Faced the same problem and what I did as a workaround is to create an Interface to be implemented by the model. On the listener, I then check if the model is an instance of an interface then perform the necessary tasks. I'm also interested to know a better approach? Thanks!

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by macagoraga** [comment]
@yajra did you found a better approuch?

I see that I can get the class name without creating interface like:

```

    public function handle(RepositoryEntityCreated $event)
    {
        Log::info('action: ' . $event->getAction() . ' - model: ' . get_class($event->getModel()));
    }

```
