### ISSUE TITLE
Clean Cache Listener

### ISSUE THREAD

**Issue by liangguohuan** [andersao/l5-repository#727]
Why not use cache tag fucntion for cleanning cache in a file `CleanCacheRepository.php`.
Store all repository cache keys in a file `repository-cache-keys.json`, and clean the repository cache when create，update，delete entry in repository  in a loop everytime. Is it a problem?

**Comment by bsormagec** [comment]
We are open to implemented new cache cleaning model PR. Just do it @liangguohuan :)
