### ISSUE TITLE
Add Laravel 8 support

### ISSUE THREAD

**Issue by Jamesking56** [andersao/l5-repository#732]
Add support for Laravel 8

**Comment by masroore** [comment]
Please upgrade to the latest laravel v8

**Comment by ibkhall** [comment]
Please upgrade

**Comment by sairam2188** [comment]
Please add support for Laravel 8

**Comment by masroore** [comment]
In the meantime, you can use this repo: 
[https://github.com/masroore/laravel-repository](https://github.com/masroore/laravel-repository)

In your `composer.json` file:

      "repositories": [
          { "type": "git", "url": "https://github.com/masroore/laravel-validation" },
          { "type": "git", "url": "https://github.com/masroore/laravel-repository" }
      ],
      "require": {
          ...
          "prettus/laravel-validation": "dev-master",
          "prettus/laravel-repository": "dev-master"
      },

**Comment by bsormagec** [comment]
Fixed #730
