### ISSUE TITLE
Model instance as a parameter for update / delete ?

### ISSUE THREAD

**Issue by DarKDinDoN** [andersao/l5-repository#75]
Hello,

I have noticed that you are using the findOrFail method for the following methods : update or delete.

But what if the app retrieves the model with an other attribute than the ID ?

Example :
The user request a blog article. The url is http://myblog.com/posts/the-prettus-repository.
The route parameter is not an ID but a slug. Since the repository accepts only an ID, we should find the model by its slug attribute and then pass the model's ID to the update / delete method. And then, the repository makes another query to retrieve (again) the model from the database.

So we perform two queries for a simple update or delete, when we can perform only one query. If there is any FormRequest with a unique check involved, it makes three requests for the same model.

What about :
- Allow to pass the model instance to the update / delete method so that the repository doesn't make another query ?
- Completely remove the find query from the update / delete method since i'm not sure finding the model to be updated or deleted is the repository responsibility ? (at least not in the update / delete method)

Thanks,

**Comment by DarKDinDoN** [comment]
Also,

When using softDeletes, you can not update a deleted model because the update method use the findOrFail() method without the "withTrashed()" parameter.

And it seems impossible to change the way the update method retrieves the model instance.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by mrgrain** [comment]
You could just overwrite the update method for your special post repository or add a new `updateBySlug()` / `updateByModel`.

I agree that update and create should use scopes/criteria as well.
