### ISSUE TITLE
L9 Command "make:rest-controller" is not defined

### ISSUE THREAD

**Issue by blackWhaleDev** [andersao/l5-repository#777]
in Laravel 9 make:entity not working

![Screenshot from 2022-04-08 15-26-37](https://user-images.githubusercontent.com/66624615/162435316-bde438eb-92d8-40c8-ae1c-335b574d650a.png)

**Comment by g88827929g** [comment]
I have the same error too

**Comment by JamesKid** [comment]
I have the same errot too, any otther solutions?  my laravel version is laravel 9.8

**Comment by blackWhaleDev** [comment]
Fixed after reinstalling the package
