### ISSUE TITLE
Add Laravel 10 support

### ISSUE THREAD

**Issue by slps970093** [andersao/l5-repository#786]

**Comment by sadhakbj** [comment]
https://github.com/andersao/l5-repository/pull/788

**Comment by Remcojansen88** [comment]
Composer still fails on dependency (prettus/laravel-validation)

**Comment by andersao** [comment]
Hey guys! It is done. The `prettus/laravel-validation` was also updated.

**Comment by sadhakbj** [comment]
@slps970093 I guess this issue can be closed. Let's close this.
