### ISSUE TITLE
Need Laravel 11 Support

### ISSUE THREAD

**Issue by iEgria** [andersao/l5-repository#806]
Since Laravel 11 was released yesterday, this package requires compatibility with Laravel 11 in order to function properly.

**Comment by uar-goran-grbic** [comment]
It requires update of `laravel-validator` repository first, which already has [PR](https://github.com/andersao/laravel-validator/pull/52) waiting to be merged into.

**Comment by angelej** [comment]
I highly recommend **not use this package** as the maintainer didn't respond to any bug or security related topics.
There are also tons of unanswered pull requests, some of them are even 5 years old.

**Comment by iEgria** [comment]
> I highly recommend **not use this package** as the maintainer didn't respond to any bug or security related topics. There are also tons of unanswered pull requests, some of them are even 5 years old.

i will if found better alternate using laravel repository pattern

**Comment by matinwd** [comment]
> > I highly recommend **not use this package** as the maintainer didn't respond to any bug or security related topics. There are also tons of unanswered pull requests, some of them are even 5 years old.
> 
> i will if found better alternate using laravel repository pattern

Any idea for alternative

**Comment by eleftrik** [comment]
@andersao Is this project still maintained? Thanks

**Comment by inuryyev** [comment]
any update?

**Comment by andersao** [comment]
Hey everyone! Sorry to not reply here, I'm really very busy lately and I can't actively  maintain this project anymore. 

If anyone would be able to help me on it we can keep it active, if not I'll retire it and keep it as a legacy project.

But I'm accepting volunteers to help in the project.

**Comment by Remcojansen88** [comment]
Added PR to use the updated version of prettus/laravel-validation
https://github.com/andersao/l5-repository/pull/809

**Comment by eullercdr** [comment]
> Added PR to use the updated version of prettus/laravel-validation #809

Done! Could you test the new release please?

**Comment by Remcojansen88** [comment]
Did the first tests and everything seems to work fine

**Comment by angelej** [comment]
@andersao , @eullercdr nice to have you both back. Since you officially support laravel 11 you may be interested in keeping us all safe. Months ago, I submitted detailed information to both of you about a critical vulnerability in this package. I also developed a fix (see https://github.com/andersao/l5-repository/pull/805) which got rejected without any reason.

I hope you see the urgency and take the necessary steps to keep this package and it's users safe.
You can always contact me if you need further information.
