### ISSUE TITLE
Error with CacheableInterface

### ISSUE THREAD

**Issue by florentsorel** [andersao/l5-repository#82]
Hi,

I use your package and for the ```Role``` model I have a ```RoleRepository```. I have an error if I implements cache in my app.

```php
<?php

namespace App\Models;

use Dimsav\Translatable\Translatable;
use Prettus\Repository\Contracts\CacheableInterface;
use Prettus\Repository\Traits\CacheableRepository;
use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole implements CacheableInterface
{
	use CacheableRepository, Translatable;

	/**
	 * @var array
	 */
	protected $translatedAttributes = ['display_name', 'description'];

	/**
	 * @var array
	 */
	protected $fillable = ['name'];

	/**
	 * @var array
	 */
	protected $with = ['translations'];
}
```

Error:
```
FatalErrorException in Role.php line 28:
Cannot make static method Illuminate\Database\Eloquent\Model::all() non static in class Prettus\Repository\Traits\CacheableRepository
```

It's an incompatibility with L 5.1.x ?

**Comment by andersao** [comment]
Hi @Rtransat.
I will test it.

**Comment by dusterio** [comment]
Well, if you look into CacheableRepository, it does definitely try to override a static method all() 

And all() is static for a reason...

**Comment by Rtransat** [comment]
Yes I know that ;). But why the method in the trait fails in my application ?

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by geraldarcega** [comment]
Hi! I also encounter the same problem. How did you fix it?! The issues is closed but there's no solution posted. TIA!
