### ISSUE TITLE
'findWhereIn' and 'findWhereNotIn' missing in 'RepositoryInterface'

### ISSUE THREAD

**Issue by mrgrain** [andersao/l5-repository#83]
According to the [documentation](https://github.com/andersao/l5-repository#prettusrepositorycontractsrepositoryinterface) `findWhereIn` and `findWhereNotIn` should be defined in the `RepositoryInterface`. But they are not. 

This seems to be a simple mistake and I'll add a PR to fix it.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
