### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::findWhere() 

### ISSUE THREAD

**Issue by maxi032** [andersao/l5-repository#85]
In my view composer I have

<code>
<?php namespace App\Composers;
use App\Repositories\PostRepository;

class FrontComposer
{
    
    protected $postRepo;

    public function __construct(PostRepository $postRepo)
    {
        
        $this->postRepo = $postRepo;
    }

    public function compose($view)
    {
        $view->with([
            'languages' => \LaravelLocalization::getSupportedLocales(),
            'posts' => $this->postRepo->getPostsByLanguage(\LaravelLocalization::getCurrentLocale())
        ]);
    }

}
</code>

My repository class looks like
<code>
<?php namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Contracts\CacheableInterface;
use Prettus\Repository\Traits\CacheableRepository;
use Illuminate\Database\Eloquent\Builder;

class PostRepositoryEloquent extends BaseRepository implements PostRepository, CacheableInterface {
	
	use CacheableRepository;
	  
    protected $rules = [];

    public function model()
    {
        return 'App\Entities\Post';
    }
   
	public function getPostsByLanguage($lang){
		return $this->model->findWhere(['lang'=>$lang]);
	}
}
</code>

**Comment by uyab** [comment]
I think it should `$this->findWhere` instead of `$this->model->findWhere`

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
