### ISSUE TITLE
Validators with Repository isn't executed

### ISSUE THREAD

**Issue by silasrm** [andersao/l5-repository#86]
Hi,

I'm using doc example https://github.com/andersao/l5-repository#enabling-validator-in-your-repository but not happening.

Laravel version: 5.1.13
L5-repository: 2.1.4
Laravel-validation: 1.1.4

```php
<?php

namespace SON\Validators;

use \Prettus\Validator\LaravelValidator;

class ChapterValidator extends LaravelValidator
{
    protected $rules = [
        'name' => 'min:3',
        'order' => 'required',
    ];
}
```

```php
<?php 
//...
class ChapterRepositoryEloquent extends BaseRepository implements ChapterRepository
{
    //..

    public function validator()
    {
        return "SON\\Validators\\ChapterValidator";
    }
}
```

```php
<?php 
//...
public function store($courseId)
    {
        //...

        return redirect()->route('admin.courses.chapters.index', ['courseId' => $courseId]);
    }
```

Thank's!

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
