### ISSUE TITLE
Doesn't work on laravel 5.0 : App\UnivRepository does not exist

### ISSUE THREAD

**Issue by husnulhamidiah** [andersao/l5-repository#88]
I have been installed this package on laravel 5.0 and I follow your instructions in readme.md precisely..
But when I run my app I always get 

App\UnivRepository does not exist..

Is there any mistake that I miss..
Or this package doesn't work on laravel 5..

**Comment by uyab** [comment]
It's look like a namespace problem, can you provide full declaration of UnivRepository and how you call it?

**Comment by husnulhamidiah** [comment]
Silly of me. You're right.
It's all about namespace.
