### ISSUE TITLE
Where clausules depending on input vars

### ISSUE THREAD

**Issue by sangar82** [andersao/l5-repository#89]
How can I achieve this?
I need to add where clausules depending Input vars. Something like:
````php
$users = $this->repository->where(function($query){
    if (Input::get('email') != "")
        $query->where('email', '=', Input::get('email'));
    if (Input::get('type') != "")
        $query->where('type', '=', Input::get('type'));
})->paginate($this->per_page);
````

I try with this but didn't work
````php
$users = $this->repository->where(function($query){
    if (Input::get('email') != "")
        $query->where('email','<>', Input::get('email'));
    if (Input::get('type') != "")
        $query->where('type','<>', Input::get('type'));
    return $query;
})->paginate($this->per_page);
````

Also with this, and didn't work
````php
$users = $this->repository->findWhere([['id', '>', 1]])->paginate($this->per_page);
````

Any help, please?

**Comment by uyab** [comment]
According to documentation, repository doesnt have `where ` function. There is `findWhere` but it is not chainable so you cannot call `paginate` after it. I think you should utilize Criteria to solve your problem.

**Comment by sangar82** [comment]
I´ve extended BaseRepository to solve my needs

Thanks!

**Comment by nateritter** [comment]
@sangar82 I'd like to know how you extended the BaseRepository to make chainable methods.
