### ISSUE TITLE
How to response the error from ValidatorException when using restful API?

### ISSUE THREAD

**Issue by DesmondPang** [andersao/l5-repository#90]
How to response the error from ValidatorException when using restful API? Now I only got  HTTP/1.0 500 Internal Server Error and show <Response body is empty>

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by ionut-tanasa** [comment]
You have to catch the exception and return your error response.
