### ISSUE TITLE
Adding criteria to related model

### ISSUE THREAD

**Issue by walterdis** [andersao/l5-repository#91]
Hello.

I'm trying to show all posts with categories (including the excluded ones).

For that i'm using:

$this->repository->pushCriteria(new LastPublishedPostsCriteria());
$this->repository->pushCriteria(new WithTrashedCriteria());

$posts = $this->repository->with('category')->paginate();

Debbuging the query i found that the post query is right but not the category because it's fetching only the active ones:
select * from `blog_categories` where `blog_categories`.`deleted_at` is null and `blog_categories`.`id` in ('1', '3', '4', '2')

Is there anyway to add a "WithTrashed" criteria to the category when i use with('category')?

Thanks

**Comment by henninghorn** [comment]
@walterdis 

You could add criterias on your category relation on the model itself.

Or you could drop the with() method and create another criteria and do something like this:

````php
function apply($model) {
    $model->with(['category' => function($query) {
      $query->where();
    }]);
  }
````

See (Eager Load Constraints) : http://laravel.com/docs/5.0/eloquent#eager-loading

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
