### ISSUE TITLE
Question : How does all() / lists work with relationships ?

### ISSUE THREAD

**Issue by geekosophe** [andersao/l5-repository#99]
Hi,

Thanks for this package !
I need help to do something quite basic : I want to retrieve only few columns on a relationship.
I have 2 tables : themes and languages. I wanted to retrieve specific columns of both tables and I noticed something strange : 

This block of code works perfectly fine (I retrieve only the two meaningful columns at the end): 
```
$themes = $this->themeRepo->with(['language'])->all()->lists('description','id');
$languages =  $this->themeRepo->with(['language'])->all()->lists('language.name','language.id');
```

But when I want to do it in one line : 
```
 $test = $this->themeRepo->with(['language'])->all()->lists('description','id','language.name','language.id');
```
I get the same result as `$themes` before, without any data about language.

I also tried to add an array with alias inside all() but it complains about the inexistence of the columns language.

Do you have any input about it ? I know I'm missing something but can't figure out what.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
